// Generated by MaterialKolor Builder 2.0.0 for MaterialKolor 6.0.0.
// Open this theme in the builder at https://materialkolor.com/t/AdllOwAAAAE_Z1CkYltxfVJgsyYeYF1iYF1mIQ

package com.example.theme

import androidx.compose.ui.graphics.Color

val SeedColor = Color(0xFFD9653B)

val Primary = Color(0xFF6750A4)

val Secondary = Color(0xFF625B71)

val Tertiary = Color(0xFF7D5260)

val Neutral = Color(0xFF605D62)

val NeutralVariant = Color(0xFF605D66)

val Error = Color(0xFFB3261E)
