// Generated by MaterialKolor Builder 2.0.0 for MaterialKolor 6.0.0.
// Open this theme in the builder at https://materialkolor.com/t/AdllOwACAADF
// Swap to material-kolor-fluent when it is available, and the colors animate once it is.

package com.example.theme

import androidx.compose.foundation.isSystemInDarkTheme
import androidx.compose.runtime.Composable
import androidx.compose.runtime.remember
import com.materialkolor.ktx.rememberDynamicScheme
import com.materialkolor.ktx.toneColor
import com.materialkolor.palettes.TonalPalette
import io.github.composefluent.Colors
import io.github.composefluent.FluentTheme
import io.github.composefluent.Shades

@Composable
fun AppTheme(
    isDark: Boolean = isSystemInDarkTheme(),
    content: @Composable () -> Unit,
) {
    val scheme = rememberDynamicScheme(
        seedColor = SeedColor,
        isDark = isDark,
    )
    val colors = remember(scheme) {
        Colors(
            shades = scheme.primaryPalette.toShades(),
            darkMode = isDark,
        )
    }

    FluentTheme(
        colors = colors,
        content = content,
    )
}

private fun TonalPalette.toShades(): Shades {
    val base = toneColor(50)
    val light1 = toneColor(60)
    val light2 = toneColor(80)
    val light3 = toneColor(90)
    val dark1 = toneColor(40)
    val dark2 = toneColor(30)
    val dark3 = toneColor(15)

    return Shades(
        base = base,
        light1 = light1,
        light2 = light2,
        light3 = light3,
        dark1 = dark1,
        dark2 = dark2,
        dark3 = dark3,
    )
}
