package com.materialkolor.builder.codegen.dsl

import com.materialkolor.builder.codegen.symbol.Symbol
import com.materialkolor.builder.codegen.symbol.SymbolKind
import com.materialkolor.builder.codegen.symbol.TestSymbols
import com.materialkolor.builder.codegen.text.Literals
import kotlin.test.Test
import kotlin.test.assertEquals
import kotlin.test.assertFailsWith
import kotlin.test.assertTrue

private val ComposableLambda = lambdaType(annotations = listOf(TestSymbols.Composable))

class KotlinFileBuilderTest {
    @Test
    fun kotlinFile_themeFunction_writesTheWholeFile() {
        val file = kotlinFile(path = "Theme.kt", packageName = "com.example") {
            function(name = "AppTheme", annotations = listOf(TestSymbols.Composable)) {
                parameter("isDark", TestSymbols.Boolean, default = call(TestSymbols.IsSystemInDarkTheme))
                parameter("content", ComposableLambda)
                body {
                    call(TestSymbols.DynamicMaterialTheme) {
                        argument("seedColor", ref("SeedColor"))
                        optionalArgument("contrastLevel", null)
                        argument("content", ref("content"))
                    }
                }
            }
        }

        val expected =
            """
            package com.example

            import androidx.compose.foundation.isSystemInDarkTheme
            import androidx.compose.runtime.Composable
            import com.materialkolor.DynamicMaterialTheme

            @Composable
            fun AppTheme(
                isDark: Boolean = isSystemInDarkTheme(),
                content: @Composable () -> Unit,
            ) {
                DynamicMaterialTheme(seedColor = SeedColor, content = content)
            }

            """.trimIndent()

        assertEquals(expected, file.text)
        assertEquals("Theme.kt", file.path)
        assertEquals(Language.Kotlin, file.language)
    }

    @Test
    fun kotlinFile_headerAndProperties_writesColorFile() {
        val file = kotlinFile(path = "Color.kt", packageName = "com.example.ui.theme") {
            header(
                listOf(
                    "Generated by MaterialKolor Builder 2.0.0 for MaterialKolor 6.0.0.",
                    "Open this theme in the builder at https://materialkolor.com/t/AdllOwAAAAAT",
                ),
            )
            property("SeedColor", Literals.colorLiteral(-0x98AF5C))
            property("Primary", Literals.colorLiteral(-0x98AF5C), type = type(TestSymbols.Color))
        }

        val expected =
            """
            // Generated by MaterialKolor Builder 2.0.0 for MaterialKolor 6.0.0.
            // Open this theme in the builder at https://materialkolor.com/t/AdllOwAAAAAT

            package com.example.ui.theme

            import androidx.compose.ui.graphics.Color

            val SeedColor = Color(0xFF6750A4)

            val Primary: Color = Color(0xFF6750A4)

            """.trimIndent()

        assertEquals(expected, file.text)
    }

    @Test
    fun kotlinFile_singleParameter_keepsTheSignatureOnOneLine() {
        val file = kotlinFile(path = "Theme.kt", packageName = "com.example") {
            function(name = "AppTheme", annotations = listOf(TestSymbols.Composable)) {
                parameter("content", ComposableLambda)
                body {
                    call("content")
                }
            }
        }

        val expected =
            """
            package com.example

            import androidx.compose.runtime.Composable

            @Composable
            fun AppTheme(content: @Composable () -> Unit) {
                content()
            }

            """.trimIndent()

        assertEquals(expected, file.text)
    }

    @Test
    fun kotlinFile_repeatedAndUnusedSymbols_importsEachOnceAndInOrder() {
        val motionScheme = Symbol("androidx.compose.material3", "MotionScheme", SymbolKind.Class)
        val colorSpec = Symbol("com.materialkolor.dynamiccolor", "ColorSpec", SymbolKind.Class)
        val unused = Symbol("com.materialkolor", "PaletteStyle", SymbolKind.Class)

        val file = kotlinFile(path = "Theme.kt", packageName = "com.example") {
            function(name = "AppTheme") {
                body {
                    call(TestSymbols.DynamicMaterialTheme) {
                        argument("motionScheme", call(motionScheme))
                        argument("specVersion", ref(colorSpec))
                        argument("fallback", ref(colorSpec))
                        argument("count", Literals.int(1))
                    }
                }
            }
        }

        val imports = file.text.lines().filter { it.startsWith("import ") }

        assertEquals(
            listOf(
                "import androidx.compose.material3.MotionScheme",
                "import com.materialkolor.DynamicMaterialTheme",
                "import com.materialkolor.dynamiccolor.ColorSpec",
            ),
            imports,
        )
        assertTrue(unused.qualifiedName !in file.text)
    }

    @Test
    fun kotlinFile_symbolInTheSamePackage_doesNotImportIt() {
        val neighbour = Symbol("com.example", "Neighbour", SymbolKind.Class)

        val file = kotlinFile(path = "Theme.kt", packageName = "com.example") {
            property("value", ref(neighbour))
        }

        assertTrue("import" !in file.text)
    }

    @Test
    fun kotlinFile_callPastTheColumnLimit_breaksWithTrailingCommas() {
        val file = kotlinFile(path = "Theme.kt", packageName = "com.example") {
            function(name = "AppTheme", annotations = listOf(TestSymbols.Composable)) {
                parameter("isDark", TestSymbols.Boolean, default = call(TestSymbols.IsSystemInDarkTheme))
                parameter("useDarkerSurfacesInTheAmoledVariant", TestSymbols.Boolean)
                parameter("content", ComposableLambda)
                body {
                    call(TestSymbols.DynamicMaterialTheme) {
                        argument("seedColor", ref("SeedColor"))
                        argument("isDark", ref("isDark"))
                        argument("isAmoled", ref("useDarkerSurfacesInTheAmoledVariant"))
                        argument("contrastLevel", Literals.decimal(-50))
                        argument("content", ref("content"))
                    }
                }
            }
        }

        val expected =
            """
            package com.example

            import androidx.compose.foundation.isSystemInDarkTheme
            import androidx.compose.runtime.Composable
            import com.materialkolor.DynamicMaterialTheme

            @Composable
            fun AppTheme(
                isDark: Boolean = isSystemInDarkTheme(),
                useDarkerSurfacesInTheAmoledVariant: Boolean,
                content: @Composable () -> Unit,
            ) {
                DynamicMaterialTheme(
                    seedColor = SeedColor,
                    isDark = isDark,
                    isAmoled = useDarkerSurfacesInTheAmoledVariant,
                    contrastLevel = -0.5,
                    content = content,
                )
            }

            """.trimIndent()

        assertEquals(expected, file.text)
        assertTrue(file.text.lines().all { it.length <= MAX_LINE_LENGTH })
    }

    @Test
    fun kotlinFile_multilineCall_breaksEvenWhenItWouldFit() {
        val file = kotlinFile(path = "Theme.kt", packageName = "com.example") {
            function(name = "AppTheme") {
                body {
                    call(TestSymbols.DynamicMaterialTheme, multiline = true) {
                        argument("seedColor", ref("SeedColor"))
                        argument("content", ref("content"))
                    }
                }
            }
        }

        val expected =
            """
            package com.example

            import com.materialkolor.DynamicMaterialTheme

            fun AppTheme() {
                DynamicMaterialTheme(
                    seedColor = SeedColor,
                    content = content,
                )
            }

            """.trimIndent()

        assertEquals(expected, file.text)
    }

    @Test
    fun kotlinFile_commentBeforeDeclaration_staysGluedToIt() {
        val file = kotlinFile(path = "Color.kt", packageName = "com.example") {
            comment("The seed every other role is derived from.")
            property("SeedColor", Literals.colorLiteral(-0x98AF5C))
        }

        val expected =
            """
            package com.example

            import androidx.compose.ui.graphics.Color

            // The seed every other role is derived from.
            val SeedColor = Color(0xFF6750A4)

            """.trimIndent()

        assertEquals(expected, file.text)
    }

    @Test
    fun kotlinFile_returnAndLocalValue_writesTheBody() {
        val file = kotlinFile(path = "Scheme.kt", packageName = "com.example") {
            function(name = "scheme", returns = type(TestSymbols.Color)) {
                body {
                    assign("seed", Literals.colorLiteral(-0x98AF5C))
                    blankLine()
                    returns(ref("seed"))
                }
            }
        }

        val expected =
            """
            package com.example

            import androidx.compose.ui.graphics.Color

            fun scheme(): Color {
                val seed = Color(0xFF6750A4)

                return seed
            }

            """.trimIndent()

        assertEquals(expected, file.text)
    }

    @Test
    fun generatedFile_colorLiteral_carriesTheArgbOnTheToken() {
        val file = kotlinFile(path = "Color.kt", packageName = "com.example") {
            property("SeedColor", Literals.colorLiteral(-0x98AF5C))
        }

        val colorTokens = file.lines.flatten().filter { it.kind == TokenKind.ColorLiteral }

        assertEquals(1, colorTokens.size)
        assertEquals("0xFF6750A4", colorTokens.single().text)
        assertEquals(-0x98AF5C, colorTokens.single().color)
    }

    @Test
    fun kotlinFile_callAsAValue_assignsAndReturnsIt() {
        val file = kotlinFile(path = "Scheme.kt", packageName = "com.example") {
            function(name = "scheme", returns = type(TestSymbols.Color)) {
                body {
                    assign(
                        name = "theme",
                        value = callOf(TestSymbols.DynamicMaterialTheme) {
                            argument("seedColor", ref("SeedColor"))
                        },
                    )
                    returns(callOf("shade") { argument(ref("theme")) })
                }
            }
        }

        val expected =
            """
            package com.example

            import androidx.compose.ui.graphics.Color
            import com.materialkolor.DynamicMaterialTheme

            fun scheme(): Color {
                val theme = DynamicMaterialTheme(seedColor = SeedColor)
                return shade(theme)
            }

            """.trimIndent()

        assertEquals(expected, file.text)
    }

    @Test
    fun kotlinFile_twoSymbolsSharingASimpleName_failsNamingBothOfThem() {
        val composeColor = Symbol("androidx.compose.ui.graphics", "Color", SymbolKind.Class)
        val kolorColor = Symbol("com.materialkolor.ktx", "Color", SymbolKind.Class)

        val failure = assertFailsWith<IllegalArgumentException> {
            kotlinFile(path = "Theme.kt", packageName = "com.example") {
                property("first", ref(composeColor))
                property("second", ref(kolorColor))
            }
        }

        val message = failure.message.orEmpty()
        assertTrue("androidx.compose.ui.graphics.Color" in message, message)
        assertTrue("com.materialkolor.ktx.Color" in message, message)
    }

    @Test
    fun kotlinFile_blankHeaderAndComment_writeBareSlashes() {
        val file = kotlinFile(path = "Color.kt", packageName = "com.example") {
            header(listOf("Generated by MaterialKolor Builder.", ""))
            comment("")
            property("Count", Literals.int(1))
        }

        val expected =
            """
            // Generated by MaterialKolor Builder.
            //

            package com.example

            //
            val Count = 1

            """.trimIndent()

        assertEquals(expected, file.text)
        assertTrue(file.text.lines().none { it.endsWith(" ") })
    }

    @Test
    fun kotlinFile_nestedMultilineCall_breaksTheCallAroundIt() {
        val file = kotlinFile(path = "Theme.kt", packageName = "com.example") {
            function(name = "AppTheme") {
                body {
                    call(TestSymbols.DynamicMaterialTheme) {
                        argument(
                            name = "seedColor",
                            value = call("Color", multiline = true) {
                                argument(Literals.int(1))
                            },
                        )
                    }
                }
            }
        }

        val expected =
            """
            package com.example

            import com.materialkolor.DynamicMaterialTheme

            fun AppTheme() {
                DynamicMaterialTheme(
                    seedColor = Color(
                        1,
                    ),
                )
            }

            """.trimIndent()

        assertEquals(expected, file.text)
    }

    @Test
    fun kotlinFile_noParametersPastTheColumnLimit_keepsTheSignatureOnOneLine() {
        val file = kotlinFile(path = "Scheme.kt", packageName = "com.example") {
            function(name = "scheme", returns = type("A".repeat(MAX_LINE_LENGTH))) {
                body {
                    returns(ref("value"))
                }
            }
        }

        val signature = file.text.lines().first { it.startsWith("fun ") }

        assertTrue(signature.startsWith("fun scheme(): AAA"), signature)
        assertTrue(signature.endsWith(" {"), signature)
    }

    @Test
    fun importOrder_javaAndKotlinPackages_sortAfterEverythingElse() {
        val sorted = listOf(
            "kotlin.time.Duration",
            "java.util.UUID",
            "com.materialkolor.PaletteStyle",
            "javax.inject.Inject",
            "com.materialkolor.dynamiccolor.ColorSpec",
            "androidx.compose.runtime.Composable",
        ).sortedWith(IMPORT_ORDER)

        assertEquals(
            listOf(
                "androidx.compose.runtime.Composable",
                "com.materialkolor.PaletteStyle",
                "com.materialkolor.dynamiccolor.ColorSpec",
                "java.util.UUID",
                "javax.inject.Inject",
                "kotlin.time.Duration",
            ),
            sorted,
        )
    }
}
