// Generated by MaterialKolor Builder 2.0.0 for MaterialKolor 6.0.0.
// Open this theme in the builder at https://materialkolor.com/t/AdllO4ADAAgDAAOLGhD_tKgPAf_7_xoCmoyJcQ

package com.example.theme

import androidx.compose.runtime.Composable
import androidx.compose.runtime.Immutable
import androidx.compose.runtime.remember
import androidx.compose.ui.graphics.Color
import com.materialkolor.MaterialKolors
import com.materialkolor.dynamiccolor.ColorSpec
import com.materialkolor.ktx.rememberDynamicScheme
import com.materialkolor.ktx.toneColor

@Immutable
data class ThemeColors(
    val primary: Color,
    val onPrimary: Color,
    val primaryContainer: Color,
    val onPrimaryContainer: Color,
    val primaryPressed: Color,
    val primaryRaised: Color,
    val secondary: Color,
    val onSecondary: Color,
    val secondaryContainer: Color,
    val onSecondaryContainer: Color,
    val tertiary: Color,
    val onTertiary: Color,
    val tertiaryContainer: Color,
    val onTertiaryContainer: Color,
    val error: Color,
    val onError: Color,
    val errorContainer: Color,
    val onErrorContainer: Color,
    val surface: Color,
    val surfaceRaised: Color,
    val surfaceSunken: Color,
    val surfaceInverse: Color,
    val onSurface: Color,
    val onSurfaceInverse: Color,
    val textStrong: Color,
    val textMuted: Color,
    val borderFaint: Color,
    val borderSoft: Color,
    val borderStrong: Color,
    val scrim: Color,
    val focusRing: Color,
    val shadow: Color,
)

@Composable
fun rememberThemeColors(
    seedColor: Color,
    isDark: Boolean,
): ThemeColors {
    val scheme = rememberDynamicScheme(
        seedColor = seedColor,
        isDark = isDark,
        specVersion = ColorSpec.SpecVersion.SPEC_2021,
    )

    return remember(scheme) {
        val kolors = MaterialKolors(scheme, isAmoled = true)

        ThemeColors(
            primary = if (isDark) Color(0xFFFFB4A8) else Color(0xFF8B1A10),
            onPrimary = kolors.onPrimary(),
            primaryContainer = kolors.primaryContainer(),
            onPrimaryContainer = kolors.onPrimaryContainer(),
            primaryPressed = scheme.primaryPalette.toneColor(if (isDark) 70 else 32),
            primaryRaised = scheme.primaryPalette.toneColor(if (isDark) 88 else 46),
            secondary = kolors.secondary(),
            onSecondary = kolors.onSecondary(),
            secondaryContainer = kolors.secondaryContainer(),
            onSecondaryContainer = kolors.onSecondaryContainer(),
            tertiary = kolors.tertiary(),
            onTertiary = kolors.onTertiary(),
            tertiaryContainer = kolors.tertiaryContainer(),
            onTertiaryContainer = kolors.onTertiaryContainer(),
            error = kolors.error(),
            onError = kolors.onError(),
            errorContainer = kolors.errorContainer(),
            onErrorContainer = kolors.onErrorContainer(),
            surface = if (isDark) kolors.surface() else Color(0xFFFFFBFF),
            surfaceRaised = scheme.neutralPalette.toneColor(if (isDark) 12 else 100),
            surfaceSunken = scheme.neutralPalette.toneColor(if (isDark) 4 else 94),
            surfaceInverse = kolors.inverseSurface(),
            onSurface = kolors.onSurface(),
            onSurfaceInverse = kolors.inverseOnSurface(),
            textStrong = scheme.neutralVariantPalette.toneColor(if (isDark) 90 else 10),
            textMuted = scheme.neutralVariantPalette.toneColor(if (isDark) 70 else 40),
            borderFaint = scheme.neutralVariantPalette.toneColor(if (isDark) 22 else 92),
            borderSoft = scheme.neutralVariantPalette.toneColor(if (isDark) 32 else 85),
            borderStrong = scheme.neutralVariantPalette.toneColor(if (isDark) 65 else 55),
            scrim = kolors.scrim(),
            focusRing = scheme.primaryPalette.toneColor(if (isDark) 60 else 50),
            shadow = scheme.neutralPalette.toneColor(0),
        )
    }
}
