# Merge these into the version catalog of your own project.

[versions]
materialKolor = "6.0.0"
fluent = "v0.1.0"

[libraries]
materialKolor-fluent = { module = "com.materialkolor:material-kolor-fluent", version.ref = "materialKolor" }
fluent = { module = "io.github.compose-fluent:fluent", version.ref = "fluent" }
