// Generated by MaterialKolor Builder 2.0.0 for MaterialKolor 6.0.0.
// Open this theme in the builder at https://materialkolor.com/t/AdllOwAIAABC

package com.example.theme

import android.os.Build
import androidx.compose.foundation.isSystemInDarkTheme
import androidx.compose.material3.MaterialTheme
import androidx.compose.material3.dynamicDarkColorScheme
import androidx.compose.material3.dynamicLightColorScheme
import androidx.compose.runtime.Composable
import androidx.compose.ui.platform.LocalContext
import com.materialkolor.material3.DynamicMaterialTheme
import dev.ggoggam.inklet.InkletTheme

@Composable
fun AppTheme(
    isDark: Boolean = isSystemInDarkTheme(),
    dynamicColor: Boolean = true,
    content: @Composable () -> Unit,
) {
    val context = LocalContext.current

    if (dynamicColor && Build.VERSION.SDK_INT >= Build.VERSION_CODES.S) {
        MaterialTheme(
            colorScheme = if (isDark) dynamicDarkColorScheme(context) else dynamicLightColorScheme(context),
            content = { InkletTheme(content = content) },
        )
    } else {
        DynamicMaterialTheme(
            seedColor = SeedColor,
            isDark = isDark,
            content = { InkletTheme(content = content) },
        )
    }
}
