// Generated by MaterialKolor Builder 2.0.0 with colors from MaterialKolor 6.0.0.
// Open this theme in the builder at https://materialkolor.com/t/AdllOwICAAEBZ1CkHA

package com.example.theme

import androidx.compose.foundation.isSystemInDarkTheme
import androidx.compose.runtime.Composable
import androidx.compose.runtime.remember
import androidx.compose.ui.graphics.Color
import io.github.composefluent.Colors
import io.github.composefluent.FluentTheme
import io.github.composefluent.Shades

val LightThemeShades = Shades(
    base = Color(0xFFD9653B),
    light1 = Color(0xFFDC6A42),
    light2 = Color(0xFFDF6F49),
    light3 = Color(0xFFE27450),
    dark1 = Color(0xFF62F4D0),
    dark2 = Color(0xFF5FEFC9),
    dark3 = Color(0xFF5CEAC2),
)

val DarkThemeShades = Shades(
    base = Color(0xFFE57957),
    light1 = Color(0xFFE87E5E),
    light2 = Color(0xFFEB8365),
    light3 = Color(0xFFEE886C),
    dark1 = Color(0xFF6F08EC),
    dark2 = Color(0xFF6C03E5),
    dark3 = Color(0xFF68FEDE),
)

@Composable
fun AppTheme(
    isDark: Boolean = isSystemInDarkTheme(),
    content: @Composable () -> Unit,
) {
    val colors = remember(isDark) {
        Colors(
            shades = if (isDark) DarkThemeShades else LightThemeShades,
            darkMode = isDark,
        )
    }

    FluentTheme(
        colors = colors,
        content = content,
    )
}
