// Generated by MaterialKolor Builder 2.0.0 for MaterialKolor 6.0.0.
// Open this theme in the builder at https://materialkolor.com/t/AdllOxMEAAQBAR6I5QVCcmFuZGk

package com.example.theme

import androidx.compose.ui.graphics.Color

val SeedColor = Color(0xFFD9653B)

val BrandSeed = Color(0xFF1E88E5)
