// Generated by MaterialKolor Builder 2.0.0 for MaterialKolor 6.0.0.
// Open this theme in the builder at https://materialkolor.com/t/AdllOxMEAAQBAR6I5QVCcmFuZGk

package com.example.theme

import androidx.compose.runtime.Composable
import androidx.compose.runtime.Immutable
import androidx.compose.runtime.remember
import androidx.compose.runtime.staticCompositionLocalOf
import androidx.compose.ui.graphics.Color
import com.materialkolor.ktx.ContrastThreshold
import com.materialkolor.ktx.onTone
import com.materialkolor.ktx.rememberTonalPalette
import com.materialkolor.ktx.toneColor
import com.materialkolor.palettes.TonalPalette

@Immutable
data class ColorFamily(
    val color: Color,
    val onColor: Color,
    val colorContainer: Color,
    val onColorContainer: Color,
)

@Immutable
data class ExtendedColors(
    val brand: ColorFamily,
)

val LocalExtendedColors = staticCompositionLocalOf<ExtendedColors> {
    error("ExtendedColors are only provided inside AppTheme")
}

@Composable
fun rememberExtendedColors(
    seedColor: Color,
    isDark: Boolean,
): ExtendedColors {
    val brandPalette = rememberTonalPalette(
        seed = BrandSeed,
        harmonizeWith = seedColor,
    )

    return remember(brandPalette, isDark) {
        ExtendedColors(
            brand = brandPalette.colorFamily(
                tone = if (isDark) 80 else 40,
                containerTone = if (isDark) 30 else 90,
            ),
        )
    }
}

private fun TonalPalette.colorFamily(
    tone: Int,
    containerTone: Int,
    threshold: ContrastThreshold = ContrastThreshold.WCAG_AA_NORMAL_TEXT,
): ColorFamily {
    val color = toneColor(tone)
    val onColor = onTone(tone, threshold)
    val colorContainer = toneColor(containerTone)
    val onColorContainer = onTone(containerTone, threshold)

    return ColorFamily(color, onColor, colorContainer, onColorContainer)
}
