// Generated by MaterialKolor Builder 2.0.0 for MaterialKolor 6.0.0.
// Open this theme in the builder at https://materialkolor.com/t/AdllOxMEAAQBAR6I5QVCcmFuZGk

package com.example.theme

import android.os.Build
import androidx.compose.foundation.isSystemInDarkTheme
import androidx.compose.material3.ExperimentalMaterial3ExpressiveApi
import androidx.compose.material3.MaterialExpressiveTheme
import androidx.compose.material3.MotionScheme
import androidx.compose.material3.dynamicDarkColorScheme
import androidx.compose.material3.dynamicLightColorScheme
import androidx.compose.runtime.Composable
import androidx.compose.runtime.CompositionLocalProvider
import androidx.compose.ui.platform.LocalContext
import com.materialkolor.material3.DynamicMaterialExpressiveTheme

@OptIn(ExperimentalMaterial3ExpressiveApi::class)
@Composable
fun AppTheme(
    isDark: Boolean = isSystemInDarkTheme(),
    dynamicColor: Boolean = true,
    content: @Composable () -> Unit,
) {
    val extendedColors = rememberExtendedColors(
        seedColor = SeedColor,
        isDark = isDark,
    )
    val context = LocalContext.current

    CompositionLocalProvider(LocalExtendedColors provides extendedColors) {
        if (dynamicColor && Build.VERSION.SDK_INT >= Build.VERSION_CODES.S) {
            MaterialExpressiveTheme(
                colorScheme = if (isDark) dynamicDarkColorScheme(context) else dynamicLightColorScheme(context),
                motionScheme = MotionScheme.expressive(),
                content = content,
            )
        } else {
            DynamicMaterialExpressiveTheme(
                seedColor = SeedColor,
                motionScheme = MotionScheme.expressive(),
                isDark = isDark,
                content = content,
            )
        }
    }
}
