// Generated by MaterialKolor Builder 2.0.0 for MaterialKolor 6.0.0.
// Open this theme in the builder at https://materialkolor.com/t/AdllOwADAAQDAR6I5QVCcmFuZABDoEcHU3VjY2Vzcwf7jAAHV2FybmluZzJfRhQC4g

package com.example.theme

import androidx.compose.ui.graphics.Color

val SeedColor = Color(0xFFD9653B)

val BrandSeed = Color(0xFF1E88E5)

val SuccessSeed = Color(0xFF43A047)

val WarningSeed = Color(0xFFFB8C00)
