// Generated by MaterialKolor Builder 2.0.0 for MaterialKolor 6.0.0.
// Open this theme in the builder at https://materialkolor.com/t/AdllOykAAAIufTId

package com.example.theme

import androidx.compose.ui.graphics.Color

val SeedColor = Color(0xFFD9653B)

val TertiarySeedColor = Color(0xFF2E7D32)
