package com.materialkolor.builder.codegen

/**
 * The CRC-32 of every golden case, as `GoldenDigest` works it out.
 *
 * The JVM golden harness writes this file whenever it updates the goldens, so rather than editing
 * it by hand, run the codegen jvmTest task with -Pgolden.update=true.
 */
internal object GoldenHashes {
    val cases: Map<String, Long> = mapOf(
        "custom-dynamic-accents" to 0xDE8612C0L,
        "custom-dynamic-cmf" to 0xE5256BEEL,
        "custom-dynamic-custom-tones" to 0x80CDD677L,
        "custom-dynamic-default" to 0x79063DDAL,
        "custom-dynamic-pins-amoled" to 0xB8FAE5CEL,
        "custom-frozen-accents-pins-amoled" to 0x73FABDFEL,
        "custom-frozen-all-contrasts" to 0x95DEE013L,
        "custom-frozen-default" to 0x1467FC7CL,
        "dsl-forms" to 0x373CA3C3L,
        "expressive-dynamic-android-dynamic-color" to 0xB4060B24L,
        "expressive-dynamic-default" to 0x6130410BL,
        "expressive-dynamic-pins" to 0x8FFC05C6L,
        "expressive-dynamic-tonal-spot-2021" to 0xD5F905D9L,
        "expressive-frozen-all-contrasts" to 0xD8FCCDCFL,
        "expressive-frozen-default" to 0x50315885L,
        "fluent-dynamic-animated" to 0x14DC982BL,
        "fluent-dynamic-default" to 0x8A2D6C7AL,
        "fluent-dynamic-inline" to 0x20C1E9C3L,
        "fluent-dynamic-inline-animated" to 0xF5785FA5L,
        "fluent-dynamic-inline-vibrant-primary-override" to 0x6D02C21AL,
        "fluent-dynamic-vibrant-primary-override" to 0x36BBBF80L,
        "fluent-frozen-all-contrasts" to 0xCD8D3FABL,
        "fluent-frozen-default" to 0xCD8D3FABL,
        "fluent-frozen-vibrant-primary-override" to 0xF451A857L,
        "header-default" to 0xB68DC275L,
        "material3-dynamic-all-overrides" to 0x76F2058EL,
        "material3-dynamic-amoled" to 0x4B42A45FL,
        "material3-dynamic-android-dynamic-color" to 0x2552258EL,
        "material3-dynamic-android-only" to 0x8FE3C2BCL,
        "material3-dynamic-animated" to 0x14FC2328L,
        "material3-dynamic-cmf" to 0x1586783BL,
        "material3-dynamic-default" to 0xC106C8E3L,
        "material3-dynamic-high-contrast" to 0x4B8AF1FFL,
        "material3-dynamic-pins" to 0xFC40E256L,
        "material3-dynamic-primary-override" to 0x6AAEEF2DL,
        "material3-dynamic-reduced-contrast" to 0x3A01E9A9L,
        "material3-dynamic-three-accents" to 0xAC3EEDF8L,
        "material3-dynamic-watch-2025" to 0x92B5CCF4L,
        "material3-frozen-accents-pins-amoled" to 0xE5D431E8L,
        "material3-frozen-all-contrasts" to 0xE0953497L,
        "material3-frozen-android-dynamic-color" to 0x0E2D34CDL,
        "material3-frozen-default" to 0xF7BE6FF7L,
        "snippets-custom-dynamic-default" to 0x606BF9FCL,
        "snippets-custom-frozen-android" to 0xFE268BAAL,
        "snippets-expressive-dynamic-android" to 0xDF9A944DL,
        "snippets-fluent-dynamic-default" to 0xB909CAA7L,
        "snippets-fluent-dynamic-inline" to 0x9261B9EBL,
        "snippets-fluent-frozen-android" to 0xAB5CECBFL,
        "snippets-material3-dynamic-android-no-catalog" to 0xCC976D1DL,
        "snippets-material3-dynamic-default" to 0x592F57D2L,
        "snippets-material3-frozen-default" to 0x660F388BL,
        "snippets-unstyled-dynamic-default" to 0xD60F19B8L,
        "snippets-unstyled-frozen-no-catalog" to 0x56017F7BL,
        "unstyled-dynamic-animated" to 0xFF08E48DL,
        "unstyled-dynamic-default" to 0x1D3BDE22L,
        "unstyled-dynamic-explicit-overrides" to 0xD467D880L,
        "unstyled-dynamic-pins" to 0x9D38113FL,
        "unstyled-dynamic-primary-override" to 0xD74617F4L,
        "unstyled-dynamic-three-accents" to 0x68FE097BL,
        "unstyled-frozen-accents-pins-amoled" to 0xE372A610L,
        "unstyled-frozen-all-contrasts" to 0x841D55F4L,
        "unstyled-frozen-default" to 0x22B4252DL,
    )
}
