// Generated by MaterialKolor Builder 2.0.0 for MaterialKolor 6.0.0.
// Open this theme in the builder at https://materialkolor.com/t/AdllOwAAAAgDAAOLGhD_tKgPAf_7_xoCmoyJlA

package com.example.theme

import androidx.compose.foundation.isSystemInDarkTheme
import androidx.compose.runtime.Composable
import androidx.compose.ui.graphics.Color
import com.materialkolor.dynamiccolor.ColorSpec
import com.materialkolor.material3.DynamicMaterialTheme
import com.materialkolor.material3.rememberDynamicMaterialThemeState

@Composable
fun AppTheme(
    isDark: Boolean = isSystemInDarkTheme(),
    content: @Composable () -> Unit,
) {
    val state = rememberDynamicMaterialThemeState(
        seedColor = SeedColor,
        isDark = isDark,
        specVersion = ColorSpec.SpecVersion.SPEC_2021,
        modifyColorScheme = { scheme ->
            scheme.copy(
                primary = if (isDark) Color(0xFFFFB4A8) else Color(0xFF8B1A10),
                surface = if (isDark) scheme.surface else Color(0xFFFFFBFF),
                outline = if (isDark) Color(0xFF9A8C89) else scheme.outline,
            )
        },
    )

    DynamicMaterialTheme(
        state = state,
        content = content,
    )
}
