package com.materialkolor.sample.customtheme.theme

import java.io.File
import kotlin.test.Test

/**
 * Rewrites the golden table when [OUTPUT_ENV_VAR] is set, and does nothing otherwise.
 *
 * The table records every tone the theme picks, so it should only change when someone meant to
 * change it. Regenerate from the repository root with an absolute output path, because the test
 * worker does not run there:
 *
 * ```
 * APP_THEME_GOLDEN_OUT="$PWD/samples/custom-theme/src/commonTest/kotlin/com/materialkolor/sample/customtheme/theme/AppThemeGoldenData.kt" \
 *   ./gradlew :samples:custom-theme:jvmTest --tests '*AppThemeGoldenWriter*' --rerun-tasks
 * ./gradlew :samples:custom-theme:spotlessApply
 * ```
 *
 * Then read the diff before committing it.
 */
class AppThemeGoldenWriter {
    @Test
    fun writeGoldenTable() {
        val target = System.getenv(OUTPUT_ENV_VAR) ?: return
        File(target).writeText(fileText())
    }

    private fun fileText(): String =
        buildString {
            appendLine("package com.materialkolor.sample.customtheme.theme")
            appendLine()
            appendLine("// Generated by AppThemeGoldenWriter. Do not hand-edit this file.")
            appendLine("// Every line is one slot of the sample theme for one seed in one mode.")
            appendLine("internal val appThemeGoldens =")
            appendLine("    \"\"\"")
            appendLine(renderAppThemeGoldens())
            appendLine("    \"\"\"")
        }

    private companion object {
        const val OUTPUT_ENV_VAR = "APP_THEME_GOLDEN_OUT"
    }
}
