// Generated by MaterialKolor Builder 2.0.0 for MaterialKolor 6.0.0.
// Open this theme in the builder at https://materialkolor.com/t/AdllOxMEAADl

package com.example.theme

import androidx.compose.foundation.isSystemInDarkTheme
import androidx.compose.material3.ExperimentalMaterial3ExpressiveApi
import androidx.compose.material3.MotionScheme
import androidx.compose.runtime.Composable
import com.materialkolor.material3.DynamicMaterialExpressiveTheme

@OptIn(ExperimentalMaterial3ExpressiveApi::class)
@Composable
fun AppTheme(
    isDark: Boolean = isSystemInDarkTheme(),
    content: @Composable () -> Unit,
) {
    DynamicMaterialExpressiveTheme(
        seedColor = SeedColor,
        motionScheme = MotionScheme.expressive(),
        isDark = isDark,
        content = content,
    )
}
