[versions]
runtime = "1.10.0"
sdk-compile = "37"
sdk-min = "21"
jvmTarget = "17"
agp = "9.3.2"
kotlin = "2.4.10"
compose-multiplatform = "1.12.0"
compose-material3 = "1.11.0-alpha07"
androidx-annotation = "1.10.0"
binaryCompatibility = "0.18.1"
dokka = "2.2.0"
publish = "0.37.0"
colormath = "3.6.1"
poko = "0.23.1"
errorProneAnnotations = "2.50.0"
kotest = "6.2.4"
ktlint = "1.8.0"
spotless = "8.10.1"
app-name = "com.materialkolor.builder"
app-version = "1.0.3"
app-code = "103"
android-compileSdk = "37"
android-targetSdk = "37"
android-minSdk = "26"
androidx-activity = "1.13.0"
androidx-activityCompose = "1.13.0"
androidx-core = "1.19.0"
androidx-lifecycle = "2.11.0"
calfFilePicker = "0.13.0"
highlights = "1.1.0"
compose-windowSizeClass = "1.11.0-alpha07"
compose-hot-reload = "1.2.0"
kotlinx-coroutines = "1.11.0"
kotlinx-datetime = "0.8.0-0.6.x-compat"
kotlinx-collections = "0.5.1"
kotlinxBrowser = "0.5.0"
kstore = "1.1.0"
kermit = "2.1.0"
ktor = "3.5.2"
material3-adaptive = "1.2.0"
material3-adaptive-suite = "1.11.0-alpha07"
materialIconsExtended = "1.7.3"
materialKolor = "5.0.0"
composeIcons = "1.1.1"
stateHolder = "3.1.0"
colorpicker = "1.2.0"
buildKonfig = "0.22.0"

[libraries]
androidx-annotation = { module = "androidx.annotation:annotation", version.ref = "androidx-annotation" }
colormath = { module = "com.github.ajalt.colormath:colormath", version.ref = "colormath" }
errorProneAnnotations = { module = "com.google.errorprone:error_prone_annotations", version.ref = "errorProneAnnotations" }
kotest-assertions = { module = "io.kotest:kotest-assertions-core", version.ref = "kotest" }
compose-foundation = { module = "org.jetbrains.compose.foundation:foundation", version.ref = "compose-multiplatform" }
compose-runtime = { module = "org.jetbrains.compose.runtime:runtime", version.ref = "compose-multiplatform" }
compose-ui = { module = "org.jetbrains.compose.ui:ui", version.ref = "compose-multiplatform" }
compose-ui-test = { module = "org.jetbrains.compose.ui:ui-test", version.ref = "compose-multiplatform" }
compose-material3 = { module = "org.jetbrains.compose.material3:material3", version.ref = "compose-material3" }
androidx-activity = { group = "androidx.activity", name = "activity", version.ref = "androidx-activity" }
androidx-activity-compose = { module = "androidx.activity:activity-compose", version.ref = "androidx-activityCompose" }
androidx-core = { group = "androidx.core", name = "core-ktx", version.ref = "androidx-core" }
androidx-lifecycle-viewmodel = { group = "org.jetbrains.androidx.lifecycle", name = "lifecycle-viewmodel", version.ref = "androidx-lifecycle" }
androidx-lifecycle-viewmodel-compose = { module = "org.jetbrains.androidx.lifecycle:lifecycle-viewmodel-compose", version.ref = "androidx-lifecycle" }
androidx-lifecycle-runtime-compose = { group = "org.jetbrains.androidx.lifecycle", name = "lifecycle-runtime-compose", version.ref = "androidx-lifecycle" }
calf-filePicker = { module = "com.mohamedrejeb.calf:calf-file-picker", version.ref = "calfFilePicker" }
compose-resources = { module = "org.jetbrains.compose.components:components-resources", version.ref = "compose-multiplatform" }
compose-ui-tooling-preview = { module = "org.jetbrains.compose.ui:ui-tooling-preview", version.ref = "compose-multiplatform" }
highlights = { module = "dev.snipme:highlights", version.ref = "highlights" }
kermit = { module = "co.touchlab:kermit", version.ref = "kermit" }
kotlinx-browser = { module = "org.jetbrains.kotlinx:kotlinx-browser", version.ref = "kotlinxBrowser" }
kstore = { module = "io.github.xxfast:kstore", version.ref = "kstore" }
kstore-file = { module = "io.github.xxfast:kstore-file", version.ref = "kstore" }
kstore-storage = { module = "io.github.xxfast:kstore-storage", version.ref = "kstore" }
kotlinx-coroutines-core = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-core", version.ref = "kotlinx-coroutines" }
kotlinx-coroutines-android = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-android", version.ref = "kotlinx-coroutines" }
kotlinx-coroutines-guava = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-guava", version.ref = "kotlinx-coroutines" }
kotlinx-coroutines-swing = { group = "org.jetbrains.kotlinx", name = "kotlinx-coroutines-swing", version.ref = "kotlinx-coroutines" }
kotlinx-datetime = { module = "org.jetbrains.kotlinx:kotlinx-datetime", version.ref = "kotlinx-datetime" }
kotlinx-collections = { module = "org.jetbrains.kotlinx:kotlinx-collections-immutable", version.ref = "kotlinx-collections" }
ktor-http = { module = "io.ktor:ktor-http", version.ref = "ktor" }
ktor-client-core = { module = "io.ktor:ktor-client-core", version.ref = "ktor" }
ktor-client-content-negotiation = { module = "io.ktor:ktor-client-content-negotiation", version.ref = "ktor" }
ktor-serialization-kotlinx-json = { module = "io.ktor:ktor-serialization-kotlinx-json", version.ref = "ktor" }
ktor-client-okhttp = { module = "io.ktor:ktor-client-okhttp", version.ref = "ktor" }
ktor-client-darwin = { module = "io.ktor:ktor-client-darwin", version.ref = "ktor" }
ktor-client-js = { module = "io.ktor:ktor-client-js", version.ref = "ktor" }
material-icons-extended = { module = "org.jetbrains.compose.material:material-icons-extended", version.ref = "materialIconsExtended" }
material3-adaptive = { module = "org.jetbrains.compose.material3.adaptive:adaptive", version.ref = "material3-adaptive" }
material3-adaptive-layout = { module = "org.jetbrains.compose.material3.adaptive:adaptive-layout", version.ref = "material3-adaptive" }
material3-adaptive-navigation = { module = "org.jetbrains.compose.material3.adaptive:adaptive-navigation", version.ref = "material3-adaptive" }
material3-adaptive-navigation-suite = { module = "org.jetbrains.compose.material3:material3-adaptive-navigation-suite", version.ref = "material3-adaptive-suite" }
material3-windowSizeClass = { module = "org.jetbrains.compose.material3:material3-window-size-class", version.ref = "compose-windowSizeClass" }
materialKolor = { module = "com.materialkolor:material-kolor", version.ref = "materialKolor" }
materialKolor-utilities = { module = "com.materialkolor:material-color-utilities", version.ref = "materialKolor" }
stateHolder = { module = "dev.jordond.stateholder:core", version.ref = "stateHolder" }
stateHolder-viewModel = { module = "dev.jordond.stateholder:extensions-viewmodel", version.ref = "stateHolder" }
stateHolder-compose = { module = "dev.jordond.stateholder:extensions-compose", version.ref = "stateHolder" }
stateHolder-dispatcher = { module = "dev.jordond.stateholder:dispatcher", version.ref = "stateHolder" }
stateHolder-dispatcher-compose = { module = "dev.jordond.stateholder:dispatcher-compose", version.ref = "stateHolder" }
composeIcons-fontAwesome = { module = "br.com.devsrsouza.compose.icons:font-awesome", version.ref = "composeIcons" }
compose-colorpicker = { module = "com.github.skydoves:colorpicker-compose", version.ref = "colorpicker" }

[plugins]
kotlin-jvm = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }
multiplatform = { id = "org.jetbrains.kotlin.multiplatform", version.ref = "kotlin" }
compose = { id = "org.jetbrains.compose", version.ref = "compose-multiplatform" }
compose-compiler = { id = "org.jetbrains.kotlin.plugin.compose", version.ref = "kotlin" }
multiplatform-android-library = { id = "com.android.kotlin.multiplatform.library", version.ref = "agp" }
kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
binaryCompatibility = { id = "org.jetbrains.kotlinx.binary-compatibility-validator", version.ref = "binaryCompatibility" }
dokka = { id = "org.jetbrains.dokka", version.ref = "dokka" }
publish = { id = "com.vanniktech.maven.publish", version.ref = "publish" }
poko = { id = "dev.drewhamilton.poko", version.ref = "poko" }
spotless = {id = "com.diffplug.spotless", version.ref = "spotless"}
buildKonfig = { id = "com.codingfeline.buildkonfig", version.ref = "buildKonfig" }
kotlinx-serialization = { id = "org.jetbrains.kotlin.plugin.serialization", version.ref = "kotlin" }
android-application = { id = "com.android.application", version.ref = "agp" }
compose-hot-reload = { id = "org.jetbrains.compose.hot-reload", version.ref = "compose-hot-reload" }
