// Generated by MaterialKolor Builder 2.0.0 for MaterialKolor 6.0.0.
// Open this theme in the builder at https://materialkolor.com/t/AdllO4AAAAwDAR6I5QVCcmFuZABDoEcHU3VjY2Vzcwf7jAAHV2FybmluZzJfRhQCAwADixoQ_7SoDwH_-_8aApqMiZc

package com.example.theme

import androidx.compose.ui.graphics.Color

val primaryLight = Color(0xFF8B1A10)

val onPrimaryLight = Color(0xFFEE886C)

val primaryContainerLight = Color(0xFF03AB9D)

val onPrimaryContainerLight = Color(0xFF18CECE)

val inversePrimaryLight = Color(0xFF2DF1FF)

val secondaryLight = Color(0xFF431530)

val onSecondaryLight = Color(0xFF583861)

val secondaryContainerLight = Color(0xFF6D5B92)

val onSecondaryContainerLight = Color(0xFF827EC3)

val tertiaryLight = Color(0xFF97A1F4)

val onTertiaryLight = Color(0xFFACC525)

val tertiaryContainerLight = Color(0xFFC1E856)

val onTertiaryContainerLight = Color(0xFFD70B87)

val backgroundLight = Color(0xFFEC2EB8)

val onBackgroundLight = Color(0xFF0151E9)

val surfaceLight = Color(0xFFFFFBFF)

val onSurfaceLight = Color(0xFF2B984B)

val surfaceVariantLight = Color(0xFF40BB7C)

val onSurfaceVariantLight = Color(0xFF55DEAD)

val surfaceTintLight = Color(0xFF6B01DE)

val inverseSurfaceLight = Color(0xFF80250F)

val inverseOnSurfaceLight = Color(0xFF954840)

val errorLight = Color(0xFFAA6B71)

val onErrorLight = Color(0xFFBF8EA2)

val errorContainerLight = Color(0xFFD4B1D3)

val onErrorContainerLight = Color(0xFFE9D504)

val outlineLight = Color(0xFFFEF835)

val outlineVariantLight = Color(0xFF141B66)

val scrimLight = Color(0xFF293E97)

val surfaceBrightLight = Color(0xFF3E61C8)

val surfaceContainerLight = Color(0xFF68A82A)

val surfaceContainerHighLight = Color(0xFF7DCB5B)

val surfaceContainerHighestLight = Color(0xFF92EE8C)

val surfaceContainerLowLight = Color(0xFFA811BD)

val surfaceContainerLowestLight = Color(0xFFBD34EE)

val surfaceDimLight = Color(0xFF5384F9)

val primaryFixedLight = Color(0xFFD2581F)

val primaryFixedDimLight = Color(0xFFE77B50)

val onPrimaryFixedLight = Color(0xFFFC9E81)

val onPrimaryFixedVariantLight = Color(0xFF11C1B2)

val secondaryFixedLight = Color(0xFF26E4E3)

val secondaryFixedDimLight = Color(0xFF3C0814)

val onSecondaryFixedLight = Color(0xFF512B45)

val onSecondaryFixedVariantLight = Color(0xFF664E76)

val tertiaryFixedLight = Color(0xFF7B71A7)

val tertiaryFixedDimLight = Color(0xFF9094D8)

val onTertiaryFixedLight = Color(0xFFA5B809)

val onTertiaryFixedVariantLight = Color(0xFFBADB3A)

val primaryDark = Color(0xFFFFB4A8)

val onPrimaryDark = Color(0xFF6F08EC)

val primaryContainerDark = Color(0xFF842C1D)

val onPrimaryContainerDark = Color(0xFF994F4E)

val inversePrimaryDark = Color(0xFFAE727F)

val secondaryDark = Color(0xFFC395B0)

val onSecondaryDark = Color(0xFFD8B8E1)

val secondaryContainerDark = Color(0xFFEDDC12)

val onSecondaryContainerDark = Color(0xFF02FF43)

val tertiaryDark = Color(0xFF182274)

val onTertiaryDark = Color(0xFF2D45A5)

val tertiaryContainerDark = Color(0xFF4268D6)

val onTertiaryContainerDark = Color(0xFF578C07)

val backgroundDark = Color(0xFF000000)

val onBackgroundDark = Color(0xFF81D269)

val surfaceDark = Color(0xFF000000)

val onSurfaceDark = Color(0xFFAC18CB)

val surfaceVariantDark = Color(0xFFC13BFC)

val onSurfaceVariantDark = Color(0xFFD65F2D)

val surfaceTintDark = Color(0xFFEB825E)

val inverseSurfaceDark = Color(0xFF00A58F)

val inverseOnSurfaceDark = Color(0xFF15C8C0)

val errorDark = Color(0xFF2AEBF1)

val onErrorDark = Color(0xFF400F22)

val errorContainerDark = Color(0xFF553253)

val onErrorContainerDark = Color(0xFF6A5584)

val outlineDark = Color(0xFF9A8C89)

val outlineVariantDark = Color(0xFF949BE6)

val scrimDark = Color(0xFFA9BF17)

val surfaceBrightDark = Color(0xFFBEE248)

val surfaceContainerDark = Color(0xFF000000)

val surfaceContainerHighDark = Color(0xFFFE4BDB)

val surfaceContainerHighestDark = Color(0xFF136F0C)

val surfaceContainerLowDark = Color(0xFF000000)

val surfaceContainerLowestDark = Color(0xFF000000)

val surfaceDimDark = Color(0xFF000000)

val primaryFixedDark = Color(0xFF52D89F)

val primaryFixedDimDark = Color(0xFF67FBD0)

val onPrimaryFixedDark = Color(0xFF7D1F01)

val onPrimaryFixedVariantDark = Color(0xFF924232)

val secondaryFixedDark = Color(0xFFA76563)

val secondaryFixedDimDark = Color(0xFFBC8894)

val onSecondaryFixedDark = Color(0xFFD1ABC5)

val onSecondaryFixedVariantDark = Color(0xFFE6CEF6)

val tertiaryFixedDark = Color(0xFFFBF227)

val tertiaryFixedDimDark = Color(0xFF111558)

val onTertiaryFixedDark = Color(0xFF263889)

val onTertiaryFixedVariantDark = Color(0xFF3B5BBA)
