// Generated by MaterialKolor Builder 2.0.0 for MaterialKolor 6.0.0.
// Open this theme in the builder at https://materialkolor.com/t/AdllO4AAAAwDAR6I5QVCcmFuZABDoEcHU3VjY2Vzcwf7jAAHV2FybmluZzJfRhQCAwADixoQ_7SoDwH_-_8aApqMiZc

package com.example.theme

import androidx.compose.runtime.Immutable
import androidx.compose.runtime.staticCompositionLocalOf
import androidx.compose.ui.graphics.Color

@Immutable
data class ColorFamily(
    val color: Color,
    val onColor: Color,
    val colorContainer: Color,
    val onColorContainer: Color,
)

@Immutable
data class ExtendedColors(
    val brand: ColorFamily,
    val success: ColorFamily,
    val warning: ColorFamily,
)

val LocalExtendedColors = staticCompositionLocalOf<ExtendedColors> {
    error("ExtendedColors are only provided inside AppTheme")
}

val extendedLight = ExtendedColors(
    brand = ColorFamily(
        color = Color(0xFF218DEC),
        onColor = Color(0xFF2492F3),
        colorContainer = Color(0xFF2797FA),
        onColorContainer = Color(0xFF2A9D01),
    ),
    success = ColorFamily(
        color = Color(0xFF46A54E),
        onColor = Color(0xFF49AA55),
        colorContainer = Color(0xFF4CAF5C),
        onColorContainer = Color(0xFF4FB463),
    ),
    warning = ColorFamily(
        color = Color(0xFFFE9107),
        onColor = Color(0xFF01960E),
        colorContainer = Color(0xFF049B15),
        onColorContainer = Color(0xFF07A01C),
    ),
)

val extendedDark = ExtendedColors(
    brand = ColorFamily(
        color = Color(0xFFA20E6C),
        onColor = Color(0xFFA51373),
        colorContainer = Color(0xFFA8187A),
        onColorContainer = Color(0xFFAB1D81),
    ),
    success = ColorFamily(
        color = Color(0xFFC725CE),
        onColor = Color(0xFFCA2AD5),
        colorContainer = Color(0xFFCD2FDC),
        onColorContainer = Color(0xFFD034E3),
    ),
    warning = ColorFamily(
        color = Color(0xFF7F1187),
        onColor = Color(0xFF82168E),
        colorContainer = Color(0xFF851B95),
        onColorContainer = Color(0xFF88209C),
    ),
)
