// Generated by MaterialKolor Builder 2.0.0 for MaterialKolor 6.0.0.
// Open this theme in the builder at https://materialkolor.com/t/AdllOwABAAQDAR6I5QVCcmFuZABDoEcHU3VjY2Vzcwf7jAAHV2FybmluZzJfRhQCGg

package com.example.theme

import androidx.compose.runtime.remember
import com.composeunstyled.theme.ColorScheme
import com.composeunstyled.theme.buildThemeV2
import com.materialkolor.dynamiccolor.ColorSpec
import com.materialkolor.ktx.ContrastThreshold
import com.materialkolor.ktx.onTone
import com.materialkolor.ktx.rememberDynamicScheme
import com.materialkolor.ktx.rememberTonalPalette
import com.materialkolor.ktx.toneColor
import com.materialkolor.unstyled.MaterialKolorTokens
import com.materialkolor.unstyled.toThemeValues

val AppTheme = buildThemeV2 {
    val lightScheme = rememberDynamicScheme(
        seedColor = SeedColor,
        isDark = false,
        specVersion = ColorSpec.SpecVersion.SPEC_2021,
    )
    val darkScheme = rememberDynamicScheme(
        seedColor = SeedColor,
        isDark = true,
        specVersion = ColorSpec.SpecVersion.SPEC_2021,
    )
    val brandPalette = rememberTonalPalette(
        seed = BrandSeed,
        harmonizeWith = SeedColor,
    )
    val successPalette = rememberTonalPalette(seed = SuccessSeed)
    val warningPalette = rememberTonalPalette(
        seed = WarningSeed,
        harmonizeWith = SeedColor,
    )

    properties[MaterialKolorTokens.colors] = remember(lightScheme, brandPalette, successPalette, warningPalette) {
        lightScheme.toThemeValues() + mapOf(
            ThemeTokens.brand to brandPalette.toneColor(40),
            ThemeTokens.onBrand to brandPalette.onTone(40),
            ThemeTokens.brandContainer to brandPalette.toneColor(90),
            ThemeTokens.onBrandContainer to brandPalette.onTone(90),
            ThemeTokens.success to successPalette.toneColor(40),
            ThemeTokens.onSuccess to successPalette.onTone(40),
            ThemeTokens.successContainer to successPalette.toneColor(90),
            ThemeTokens.onSuccessContainer to successPalette.onTone(90),
            ThemeTokens.warning to warningPalette.toneColor(50),
            ThemeTokens.onWarning to warningPalette.onTone(50, ContrastThreshold.WCAG_AAA_NORMAL_TEXT),
            ThemeTokens.warningContainer to warningPalette.toneColor(95),
            ThemeTokens.onWarningContainer to warningPalette.onTone(95, ContrastThreshold.WCAG_AAA_NORMAL_TEXT),
        )
    }

    colorScheme(ColorScheme.Dark) {
        properties[MaterialKolorTokens.colors] = remember(darkScheme, brandPalette, successPalette, warningPalette) {
            darkScheme.toThemeValues() + mapOf(
                ThemeTokens.brand to brandPalette.toneColor(80),
                ThemeTokens.onBrand to brandPalette.onTone(80),
                ThemeTokens.brandContainer to brandPalette.toneColor(30),
                ThemeTokens.onBrandContainer to brandPalette.onTone(30),
                ThemeTokens.success to successPalette.toneColor(80),
                ThemeTokens.onSuccess to successPalette.onTone(80),
                ThemeTokens.successContainer to successPalette.toneColor(30),
                ThemeTokens.onSuccessContainer to successPalette.onTone(30),
                ThemeTokens.warning to warningPalette.toneColor(70),
                ThemeTokens.onWarning to warningPalette.onTone(70, ContrastThreshold.WCAG_AAA_NORMAL_TEXT),
                ThemeTokens.warningContainer to warningPalette.toneColor(20),
                ThemeTokens.onWarningContainer to warningPalette.onTone(20, ContrastThreshold.WCAG_AAA_NORMAL_TEXT),
            )
        }
    }
}
