// Generated by MaterialKolor Builder 2.0.0 for MaterialKolor 6.0.0.
// Open this theme in the builder at https://materialkolor.com/t/AdllOwABAAQDAR6I5QVCcmFuZABDoEcHU3VjY2Vzcwf7jAAHV2FybmluZzJfRhQCGg

package com.example.theme

import androidx.compose.ui.graphics.Color
import com.composeunstyled.theme.ThemeToken

object ThemeTokens {
    val brand = ThemeToken<Color>("brand")

    val onBrand = ThemeToken<Color>("onBrand")

    val brandContainer = ThemeToken<Color>("brandContainer")

    val onBrandContainer = ThemeToken<Color>("onBrandContainer")

    val success = ThemeToken<Color>("success")

    val onSuccess = ThemeToken<Color>("onSuccess")

    val successContainer = ThemeToken<Color>("successContainer")

    val onSuccessContainer = ThemeToken<Color>("onSuccessContainer")

    val warning = ThemeToken<Color>("warning")

    val onWarning = ThemeToken<Color>("onWarning")

    val warningContainer = ThemeToken<Color>("warningContainer")

    val onWarningContainer = ThemeToken<Color>("onWarningContainer")
}
