// Generated by MaterialKolor Builder 2.0.0 with colors from MaterialKolor 6.0.0.
// Open this theme in the builder at https://materialkolor.com/t/AdllO4ABAAwDAR6I5QVCcmFuZABDoEcHU3VjY2Vzcwf7jAAHV2FybmluZzJfRhQCAwADixoQ_7SoDwH_-_8aApqMiao

package com.example.theme

import androidx.compose.ui.graphics.Color
import com.composeunstyled.theme.ThemeProperty
import com.composeunstyled.theme.ThemeToken

object ThemeTokens {
    val colors = ThemeProperty<Color>("colors")

    val primary = ThemeToken<Color>("primary")

    val onPrimary = ThemeToken<Color>("onPrimary")

    val primaryContainer = ThemeToken<Color>("primaryContainer")

    val onPrimaryContainer = ThemeToken<Color>("onPrimaryContainer")

    val inversePrimary = ThemeToken<Color>("inversePrimary")

    val secondary = ThemeToken<Color>("secondary")

    val onSecondary = ThemeToken<Color>("onSecondary")

    val secondaryContainer = ThemeToken<Color>("secondaryContainer")

    val onSecondaryContainer = ThemeToken<Color>("onSecondaryContainer")

    val tertiary = ThemeToken<Color>("tertiary")

    val onTertiary = ThemeToken<Color>("onTertiary")

    val tertiaryContainer = ThemeToken<Color>("tertiaryContainer")

    val onTertiaryContainer = ThemeToken<Color>("onTertiaryContainer")

    val background = ThemeToken<Color>("background")

    val onBackground = ThemeToken<Color>("onBackground")

    val surface = ThemeToken<Color>("surface")

    val onSurface = ThemeToken<Color>("onSurface")

    val surfaceVariant = ThemeToken<Color>("surfaceVariant")

    val onSurfaceVariant = ThemeToken<Color>("onSurfaceVariant")

    val surfaceTint = ThemeToken<Color>("surfaceTint")

    val inverseSurface = ThemeToken<Color>("inverseSurface")

    val inverseOnSurface = ThemeToken<Color>("inverseOnSurface")

    val error = ThemeToken<Color>("error")

    val onError = ThemeToken<Color>("onError")

    val errorContainer = ThemeToken<Color>("errorContainer")

    val onErrorContainer = ThemeToken<Color>("onErrorContainer")

    val outline = ThemeToken<Color>("outline")

    val outlineVariant = ThemeToken<Color>("outlineVariant")

    val scrim = ThemeToken<Color>("scrim")

    val surfaceBright = ThemeToken<Color>("surfaceBright")

    val surfaceDim = ThemeToken<Color>("surfaceDim")

    val surfaceContainer = ThemeToken<Color>("surfaceContainer")

    val surfaceContainerHigh = ThemeToken<Color>("surfaceContainerHigh")

    val surfaceContainerHighest = ThemeToken<Color>("surfaceContainerHighest")

    val surfaceContainerLow = ThemeToken<Color>("surfaceContainerLow")

    val surfaceContainerLowest = ThemeToken<Color>("surfaceContainerLowest")

    val primaryFixed = ThemeToken<Color>("primaryFixed")

    val primaryFixedDim = ThemeToken<Color>("primaryFixedDim")

    val onPrimaryFixed = ThemeToken<Color>("onPrimaryFixed")

    val onPrimaryFixedVariant = ThemeToken<Color>("onPrimaryFixedVariant")

    val secondaryFixed = ThemeToken<Color>("secondaryFixed")

    val secondaryFixedDim = ThemeToken<Color>("secondaryFixedDim")

    val onSecondaryFixed = ThemeToken<Color>("onSecondaryFixed")

    val onSecondaryFixedVariant = ThemeToken<Color>("onSecondaryFixedVariant")

    val tertiaryFixed = ThemeToken<Color>("tertiaryFixed")

    val tertiaryFixedDim = ThemeToken<Color>("tertiaryFixedDim")

    val onTertiaryFixed = ThemeToken<Color>("onTertiaryFixed")

    val onTertiaryFixedVariant = ThemeToken<Color>("onTertiaryFixedVariant")

    val brand = ThemeToken<Color>("brand")

    val onBrand = ThemeToken<Color>("onBrand")

    val brandContainer = ThemeToken<Color>("brandContainer")

    val onBrandContainer = ThemeToken<Color>("onBrandContainer")

    val success = ThemeToken<Color>("success")

    val onSuccess = ThemeToken<Color>("onSuccess")

    val successContainer = ThemeToken<Color>("successContainer")

    val onSuccessContainer = ThemeToken<Color>("onSuccessContainer")

    val warning = ThemeToken<Color>("warning")

    val onWarning = ThemeToken<Color>("onWarning")

    val warningContainer = ThemeToken<Color>("warningContainer")

    val onWarningContainer = ThemeToken<Color>("onWarningContainer")
}
