package com.materialkolor.builder.codegen.text

import com.materialkolor.builder.codegen.ExportInput
import com.materialkolor.builder.codegen.ExportVersions
import com.materialkolor.builder.codegen.Fixtures
import com.materialkolor.builder.codegen.dsl.GeneratedFile
import com.materialkolor.builder.codegen.dsl.kotlinFile
import com.materialkolor.builder.domain.persist.ExportMode
import kotlin.test.Test
import kotlin.test.assertEquals
import kotlin.test.assertTrue

class HeaderTest {
    @Test
    fun lines_defaultFixture_matchesTheHeaderExactly() {
        val file = headerCaseFiles(Fixtures.Default.input).single()

        val expected =
            """
            // Generated by MaterialKolor Builder 2.0.0 for MaterialKolor 6.0.0.
            // Open this theme in the builder at https://materialkolor.com/t/AdllOwAAAAAT

            package com.example.theme
            """.trimIndent()

        assertEquals(
            expected,
            file.text
                .lines()
                .take(4)
                .joinToString("\n"),
        )
    }

    @Test
    fun lines_otherVersionsAndLink_followTheInput() {
        val input = Fixtures.Default.input.copy(
            versions = ExportVersions(
                builder = "2.1.0",
                materialKolor = "6.1.0",
                fluent = "v0.2.0",
                composeUnstyled = "2.11.0",
                composeMaterial3 = "1.12.0-alpha03",
                androidxMaterial3 = "1.5.0-alpha28",
            ),
            shareUrl = "https://example.com/t/abc",
        )

        assertEquals(
            listOf(
                "Generated by MaterialKolor Builder 2.1.0 for MaterialKolor 6.1.0.",
                "Open this theme in the builder at https://example.com/t/abc",
            ),
            Header.lines(input, ExportMode.Dynamic),
        )
    }

    @Test
    fun lines_frozen_namesTheMaterialKolorTheColorsCameFrom() {
        val input = Fixtures.Default.input

        assertEquals(
            listOf(
                "Generated by MaterialKolor Builder 2.0.0 with colors from MaterialKolor 6.0.0.",
                "Open this theme in the builder at ${input.shareUrl}",
            ),
            Header.lines(input, ExportMode.Frozen),
        )
    }

    @Test
    fun lines_everyFixtureInEitherMode_hasNoColonOutsideTheLink() {
        Fixtures.all.forEach { fixture ->
            ExportMode.entries.forEach { mode ->
                Header.lines(fixture.input, mode).forEach { line ->
                    assertTrue(':' !in line.replace(fixture.input.shareUrl, ""), "$fixture $mode: $line")
                }
            }
        }
    }
}

/**
 * The files of the `header-default` golden case, the header over the smallest file worth writing.
 *
 * It lives in common code so a wasm test can regenerate the case and check it against `GoldenHashes`.
 */
internal fun headerCaseFiles(input: ExportInput): List<GeneratedFile> =
    listOf(
        kotlinFile(path = input.sourcePath("Color.kt"), packageName = input.prefs.packageName) {
            header(Header.lines(input, ExportMode.Dynamic))
            property("SeedColor", Literals.colorLiteral(input.document.seed.value))
        },
    )
