// Generated by MaterialKolor Builder 2.0.0 for MaterialKolor 6.0.0.
// Open this theme in the builder at https://materialkolor.com/t/AdllOwAAAAQDAR6I5QVCcmFuZABDoEcHU3VjY2Vzcwf7jAAHV2FybmluZzJfRhQCZg

package com.example.theme

import androidx.compose.runtime.Composable
import androidx.compose.runtime.Immutable
import androidx.compose.runtime.remember
import androidx.compose.runtime.staticCompositionLocalOf
import androidx.compose.ui.graphics.Color
import com.materialkolor.ktx.ContrastThreshold
import com.materialkolor.ktx.onTone
import com.materialkolor.ktx.rememberTonalPalette
import com.materialkolor.ktx.toneColor
import com.materialkolor.palettes.TonalPalette

@Immutable
data class ColorFamily(
    val color: Color,
    val onColor: Color,
    val colorContainer: Color,
    val onColorContainer: Color,
)

@Immutable
data class ExtendedColors(
    val brand: ColorFamily,
    val success: ColorFamily,
    val warning: ColorFamily,
)

val LocalExtendedColors = staticCompositionLocalOf<ExtendedColors> {
    error("ExtendedColors are only provided inside AppTheme")
}

@Composable
fun rememberExtendedColors(
    seedColor: Color,
    isDark: Boolean,
): ExtendedColors {
    val brandPalette = rememberTonalPalette(seed = BrandSeed, harmonizeWith = seedColor)
    val successPalette = rememberTonalPalette(seed = SuccessSeed)
    val warningPalette = rememberTonalPalette(seed = WarningSeed, harmonizeWith = seedColor)

    return remember(brandPalette, successPalette, warningPalette, isDark) {
        ExtendedColors(
            brand = brandPalette.colorFamily(tone = if (isDark) 80 else 40, containerTone = if (isDark) 30 else 90),
            success = successPalette.colorFamily(tone = if (isDark) 80 else 40, containerTone = if (isDark) 30 else 90),
            warning = warningPalette.colorFamily(
                tone = if (isDark) 70 else 50,
                containerTone = if (isDark) 20 else 95,
                threshold = ContrastThreshold.WCAG_AAA_NORMAL_TEXT,
            ),
        )
    }
}

private fun TonalPalette.colorFamily(
    tone: Int,
    containerTone: Int,
    threshold: ContrastThreshold = ContrastThreshold.WCAG_AA_NORMAL_TEXT,
): ColorFamily {
    val color = toneColor(tone)
    val onColor = onTone(tone, threshold)
    val colorContainer = toneColor(containerTone)
    val onColorContainer = onTone(containerTone, threshold)

    return ColorFamily(color, onColor, colorContainer, onColorContainer)
}
