// Generated by MaterialKolor Builder 2.0.0 for MaterialKolor 6.0.0.
// Open this theme in the builder at https://materialkolor.com/t/AdllOwAAAAQDAR6I5QVCcmFuZABDoEcHU3VjY2Vzcwf7jAAHV2FybmluZzJfRhQCZg

package com.example.theme

import androidx.compose.foundation.isSystemInDarkTheme
import androidx.compose.runtime.Composable
import androidx.compose.runtime.CompositionLocalProvider
import com.materialkolor.material3.DynamicMaterialTheme

@Composable
fun AppTheme(
    isDark: Boolean = isSystemInDarkTheme(),
    content: @Composable () -> Unit,
) {
    val extendedColors = rememberExtendedColors(
        seedColor = SeedColor,
        isDark = isDark,
    )

    CompositionLocalProvider(LocalExtendedColors provides extendedColors) {
        DynamicMaterialTheme(
            seedColor = SeedColor,
            isDark = isDark,
            content = content,
        )
    }
}
