// Generated by MaterialKolor Builder 2.0.0 for MaterialKolor 6.0.0.
// Open this theme in the builder at https://materialkolor.com/t/AdllOwAIAAwDAR6I5QVCcmFuZABDoEcHU3VjY2Vzcwf7jAAHV2FybmluZzJfRhQCAwADixoQ_7SoDwH_-_8aApqMiXA

package com.example.theme

import androidx.compose.foundation.isSystemInDarkTheme
import androidx.compose.runtime.Composable
import androidx.compose.runtime.CompositionLocalProvider
import androidx.compose.ui.graphics.Color
import com.materialkolor.material3.DynamicMaterialTheme
import com.materialkolor.material3.rememberDynamicMaterialThemeState
import dev.ggoggam.inklet.InkletTheme

@Composable
fun AppTheme(
    isDark: Boolean = isSystemInDarkTheme(),
    content: @Composable () -> Unit,
) {
    val extendedColors = rememberExtendedColors(
        seedColor = SeedColor,
        isDark = isDark,
    )
    val state = rememberDynamicMaterialThemeState(
        seedColor = SeedColor,
        isDark = isDark,
        modifyColorScheme = { scheme ->
            scheme.copy(
                primary = if (isDark) Color(0xFFFFB4A8) else Color(0xFF8B1A10),
                surface = if (isDark) scheme.surface else Color(0xFFFFFBFF),
                outline = if (isDark) Color(0xFF9A8C89) else scheme.outline,
            )
        },
    )

    CompositionLocalProvider(LocalExtendedColors provides extendedColors) {
        DynamicMaterialTheme(
            state = state,
            content = { InkletTheme(content = content) },
        )
    }
}
