// Generated by MaterialKolor Builder 2.0.0 with colors from MaterialKolor 6.0.0.
// Open this theme in the builder at https://materialkolor.com/t/AdllOwAAAAAT

package com.example.theme

import androidx.compose.ui.graphics.Color

val primaryLight = Color(0xFFD9653B)

val onPrimaryLight = Color(0xFFEE886C)

val primaryContainerLight = Color(0xFF03AB9D)

val onPrimaryContainerLight = Color(0xFF18CECE)

val inversePrimaryLight = Color(0xFF2DF1FF)

val secondaryLight = Color(0xFF431530)

val onSecondaryLight = Color(0xFF583861)

val secondaryContainerLight = Color(0xFF6D5B92)

val onSecondaryContainerLight = Color(0xFF827EC3)

val tertiaryLight = Color(0xFF97A1F4)

val onTertiaryLight = Color(0xFFACC525)

val tertiaryContainerLight = Color(0xFFC1E856)

val onTertiaryContainerLight = Color(0xFFD70B87)

val backgroundLight = Color(0xFFEC2EB8)

val onBackgroundLight = Color(0xFF0151E9)

val surfaceLight = Color(0xFF16751A)

val onSurfaceLight = Color(0xFF2B984B)

val surfaceVariantLight = Color(0xFF40BB7C)

val onSurfaceVariantLight = Color(0xFF55DEAD)

val surfaceTintLight = Color(0xFF6B01DE)

val inverseSurfaceLight = Color(0xFF80250F)

val inverseOnSurfaceLight = Color(0xFF954840)

val errorLight = Color(0xFFAA6B71)

val onErrorLight = Color(0xFFBF8EA2)

val errorContainerLight = Color(0xFFD4B1D3)

val onErrorContainerLight = Color(0xFFE9D504)

val outlineLight = Color(0xFFFEF835)

val outlineVariantLight = Color(0xFF141B66)

val scrimLight = Color(0xFF293E97)

val surfaceBrightLight = Color(0xFF3E61C8)

val surfaceContainerLight = Color(0xFF68A82A)

val surfaceContainerHighLight = Color(0xFF7DCB5B)

val surfaceContainerHighestLight = Color(0xFF92EE8C)

val surfaceContainerLowLight = Color(0xFFA811BD)

val surfaceContainerLowestLight = Color(0xFFBD34EE)

val surfaceDimLight = Color(0xFF5384F9)

val primaryFixedLight = Color(0xFFD2581F)

val primaryFixedDimLight = Color(0xFFE77B50)

val onPrimaryFixedLight = Color(0xFFFC9E81)

val onPrimaryFixedVariantLight = Color(0xFF11C1B2)

val secondaryFixedLight = Color(0xFF26E4E3)

val secondaryFixedDimLight = Color(0xFF3C0814)

val onSecondaryFixedLight = Color(0xFF512B45)

val onSecondaryFixedVariantLight = Color(0xFF664E76)

val tertiaryFixedLight = Color(0xFF7B71A7)

val tertiaryFixedDimLight = Color(0xFF9094D8)

val onTertiaryFixedLight = Color(0xFFA5B809)

val onTertiaryFixedVariantLight = Color(0xFFBADB3A)

val primaryDark = Color(0xFF59E5BB)

val onPrimaryDark = Color(0xFF6F08EC)

val primaryContainerDark = Color(0xFF842C1D)

val onPrimaryContainerDark = Color(0xFF994F4E)

val inversePrimaryDark = Color(0xFFAE727F)

val secondaryDark = Color(0xFFC395B0)

val onSecondaryDark = Color(0xFFD8B8E1)

val secondaryContainerDark = Color(0xFFEDDC12)

val onSecondaryContainerDark = Color(0xFF02FF43)

val tertiaryDark = Color(0xFF182274)

val onTertiaryDark = Color(0xFF2D45A5)

val tertiaryContainerDark = Color(0xFF4268D6)

val onTertiaryContainerDark = Color(0xFF578C07)

val backgroundDark = Color(0xFF6CAF38)

val onBackgroundDark = Color(0xFF81D269)

val surfaceDark = Color(0xFF96F59A)

val onSurfaceDark = Color(0xFFAC18CB)

val surfaceVariantDark = Color(0xFFC13BFC)

val onSurfaceVariantDark = Color(0xFFD65F2D)

val surfaceTintDark = Color(0xFFEB825E)

val inverseSurfaceDark = Color(0xFF00A58F)

val inverseOnSurfaceDark = Color(0xFF15C8C0)

val errorDark = Color(0xFF2AEBF1)

val onErrorDark = Color(0xFF400F22)

val errorContainerDark = Color(0xFF553253)

val onErrorContainerDark = Color(0xFF6A5584)

val outlineDark = Color(0xFF7F78B5)

val outlineVariantDark = Color(0xFF949BE6)

val scrimDark = Color(0xFFA9BF17)

val surfaceBrightDark = Color(0xFFBEE248)

val surfaceContainerDark = Color(0xFFE928AA)

val surfaceContainerHighDark = Color(0xFFFE4BDB)

val surfaceContainerHighestDark = Color(0xFF136F0C)

val surfaceContainerLowDark = Color(0xFF28923D)

val surfaceContainerLowestDark = Color(0xFF3DB56E)

val surfaceDimDark = Color(0xFFD40579)

val primaryFixedDark = Color(0xFF52D89F)

val primaryFixedDimDark = Color(0xFF67FBD0)

val onPrimaryFixedDark = Color(0xFF7D1F01)

val onPrimaryFixedVariantDark = Color(0xFF924232)

val secondaryFixedDark = Color(0xFFA76563)

val secondaryFixedDimDark = Color(0xFFBC8894)

val onSecondaryFixedDark = Color(0xFFD1ABC5)

val onSecondaryFixedVariantDark = Color(0xFFE6CEF6)

val tertiaryFixedDark = Color(0xFFFBF227)

val tertiaryFixedDimDark = Color(0xFF111558)

val onTertiaryFixedDark = Color(0xFF263889)

val onTertiaryFixedVariantDark = Color(0xFF3B5BBA)

val primaryLightMediumContrast = Color(0xFF706099)

val onPrimaryLightMediumContrast = Color(0xFF8583CA)

val primaryContainerLightMediumContrast = Color(0xFF9AA6FB)

val onPrimaryContainerLightMediumContrast = Color(0xFFAFCA2C)

val inversePrimaryLightMediumContrast = Color(0xFFC4ED5D)

val secondaryLightMediumContrast = Color(0xFFDA108E)

val onSecondaryLightMediumContrast = Color(0xFFEF33BF)

val secondaryContainerLightMediumContrast = Color(0xFF0456F0)

val onSecondaryContainerLightMediumContrast = Color(0xFF197A21)

val tertiaryLightMediumContrast = Color(0xFF2E9D52)

val onTertiaryLightMediumContrast = Color(0xFF43C083)

val tertiaryContainerLightMediumContrast = Color(0xFF58E3B4)

val onTertiaryContainerLightMediumContrast = Color(0xFF6E06E5)

val backgroundLightMediumContrast = Color(0xFF832A16)

val onBackgroundLightMediumContrast = Color(0xFF984D47)

val surfaceLightMediumContrast = Color(0xFFAD7078)

val onSurfaceLightMediumContrast = Color(0xFFC293A9)

val surfaceVariantLightMediumContrast = Color(0xFFD7B6DA)

val onSurfaceVariantLightMediumContrast = Color(0xFFECDA0B)

val surfaceTintLightMediumContrast = Color(0xFF01FD3C)

val inverseSurfaceLightMediumContrast = Color(0xFF17206D)

val inverseOnSurfaceLightMediumContrast = Color(0xFF2C439E)

val errorLightMediumContrast = Color(0xFF4166CF)

val onErrorLightMediumContrast = Color(0xFF568A00)

val errorContainerLightMediumContrast = Color(0xFF6BAD31)

val onErrorContainerLightMediumContrast = Color(0xFF80D062)

val outlineLightMediumContrast = Color(0xFF95F393)

val outlineVariantLightMediumContrast = Color(0xFFAB16C4)

val scrimLightMediumContrast = Color(0xFFC039F5)

val surfaceBrightLightMediumContrast = Color(0xFFD55D26)

val surfaceContainerLightMediumContrast = Color(0xFFFFA388)

val surfaceContainerHighLightMediumContrast = Color(0xFF14C6B9)

val surfaceContainerHighestLightMediumContrast = Color(0xFF29E9EA)

val surfaceContainerLowLightMediumContrast = Color(0xFF3F0D1B)

val surfaceContainerLowestLightMediumContrast = Color(0xFF54304C)

val surfaceDimLightMediumContrast = Color(0xFFEA8057)

val primaryFixedLightMediumContrast = Color(0xFF69537D)

val primaryFixedDimLightMediumContrast = Color(0xFF7E76AE)

val onPrimaryFixedLightMediumContrast = Color(0xFF9399DF)

val onPrimaryFixedVariantLightMediumContrast = Color(0xFFA8BD10)

val secondaryFixedLightMediumContrast = Color(0xFFBDE041)

val secondaryFixedDimLightMediumContrast = Color(0xFFD30372)

val onSecondaryFixedLightMediumContrast = Color(0xFFE826A3)

val onSecondaryFixedVariantLightMediumContrast = Color(0xFFFD49D4)

val tertiaryFixedLightMediumContrast = Color(0xFF126D05)

val tertiaryFixedDimLightMediumContrast = Color(0xFF279036)

val onTertiaryFixedLightMediumContrast = Color(0xFF3CB367)

val onTertiaryFixedVariantLightMediumContrast = Color(0xFF51D698)

val primaryDarkMediumContrast = Color(0xFFF0E119)

val onPrimaryDarkMediumContrast = Color(0xFF06044A)

val primaryContainerDarkMediumContrast = Color(0xFF1B277B)

val onPrimaryContainerDarkMediumContrast = Color(0xFF304AAC)

val inversePrimaryDarkMediumContrast = Color(0xFF456DDD)

val secondaryDarkMediumContrast = Color(0xFF5A910E)

val onSecondaryDarkMediumContrast = Color(0xFF6FB43F)

val secondaryContainerDarkMediumContrast = Color(0xFF84D770)

val onSecondaryContainerDarkMediumContrast = Color(0xFF99FAA1)

val tertiaryDarkMediumContrast = Color(0xFFAF1DD2)

val onTertiaryDarkMediumContrast = Color(0xFFC44103)

val tertiaryContainerDarkMediumContrast = Color(0xFFD96434)

val onTertiaryContainerDarkMediumContrast = Color(0xFFEE8765)

val backgroundDarkMediumContrast = Color(0xFF03AA96)

val onBackgroundDarkMediumContrast = Color(0xFF18CDC7)

val surfaceDarkMediumContrast = Color(0xFF2DF0F8)

val onSurfaceDarkMediumContrast = Color(0xFF431429)

val surfaceVariantDarkMediumContrast = Color(0xFF58375A)

val onSurfaceVariantDarkMediumContrast = Color(0xFF6D5A8B)

val surfaceTintDarkMediumContrast = Color(0xFF827DBC)

val inverseSurfaceDarkMediumContrast = Color(0xFF97A0ED)

val inverseOnSurfaceDarkMediumContrast = Color(0xFFACC41E)

val errorDarkMediumContrast = Color(0xFFC1E74F)

val onErrorDarkMediumContrast = Color(0xFFD70A80)

val errorContainerDarkMediumContrast = Color(0xFFEC2DB1)

val onErrorContainerDarkMediumContrast = Color(0xFF0150E2)

val outlineDarkMediumContrast = Color(0xFF167413)

val outlineVariantDarkMediumContrast = Color(0xFF2B9744)

val scrimDarkMediumContrast = Color(0xFF40BA75)

val surfaceBrightDarkMediumContrast = Color(0xFF55DDA6)

val surfaceContainerDarkMediumContrast = Color(0xFF802408)

val surfaceContainerHighDarkMediumContrast = Color(0xFF954739)

val surfaceContainerHighestDarkMediumContrast = Color(0xFFAA6A6A)

val surfaceContainerLowDarkMediumContrast = Color(0xFFBF8D9B)

val surfaceContainerLowestDarkMediumContrast = Color(0xFFD4B0CC)

val surfaceDimDarkMediumContrast = Color(0xFF6B00D7)

val primaryFixedDarkMediumContrast = Color(0xFFE9D3FD)

val primaryFixedDimDarkMediumContrast = Color(0xFFFEF72E)

val onPrimaryFixedDarkMediumContrast = Color(0xFF141A5F)

val onPrimaryFixedVariantDarkMediumContrast = Color(0xFF293D90)

val secondaryFixedDarkMediumContrast = Color(0xFF3E60C1)

val secondaryFixedDimDarkMediumContrast = Color(0xFF5383F2)

val onSecondaryFixedDarkMediumContrast = Color(0xFF68A723)

val onSecondaryFixedVariantDarkMediumContrast = Color(0xFF7DCA54)

val tertiaryFixedDarkMediumContrast = Color(0xFF92ED85)

val tertiaryFixedDimDarkMediumContrast = Color(0xFFA810B6)

val onTertiaryFixedDarkMediumContrast = Color(0xFFBD33E7)

val onTertiaryFixedVariantDarkMediumContrast = Color(0xFFD25718)

val primaryLightHighContrast = Color(0xFF075BF7)

val onPrimaryLightHighContrast = Color(0xFF1C7F28)

val primaryContainerLightHighContrast = Color(0xFF31A259)

val onPrimaryContainerLightHighContrast = Color(0xFF46C58A)

val inversePrimaryLightHighContrast = Color(0xFF5BE8BB)

val secondaryLightHighContrast = Color(0xFF710BEC)

val onSecondaryLightHighContrast = Color(0xFF862F1D)

val secondaryContainerLightHighContrast = Color(0xFF9B524E)

val onSecondaryContainerLightHighContrast = Color(0xFFB0757F)

val tertiaryLightHighContrast = Color(0xFFC598B0)

val onTertiaryLightHighContrast = Color(0xFFDABBE1)

val tertiaryContainerLightHighContrast = Color(0xFFEFDF12)

val onTertiaryContainerLightHighContrast = Color(0xFF050243)

val backgroundLightHighContrast = Color(0xFF1A2574)

val onBackgroundLightHighContrast = Color(0xFF2F48A5)

val surfaceLightHighContrast = Color(0xFF446BD6)

val onSurfaceLightHighContrast = Color(0xFF598F07)

val surfaceVariantLightHighContrast = Color(0xFF6EB238)

val onSurfaceVariantLightHighContrast = Color(0xFF83D569)

val surfaceTintLightHighContrast = Color(0xFF98F89A)

val inverseSurfaceLightHighContrast = Color(0xFFAE1BCB)

val inverseOnSurfaceLightHighContrast = Color(0xFFC33EFC)

val errorLightHighContrast = Color(0xFFD8622D)

val onErrorLightHighContrast = Color(0xFFED855E)

val errorContainerLightHighContrast = Color(0xFF02A88F)

val onErrorContainerLightHighContrast = Color(0xFF17CBC0)

val outlineLightHighContrast = Color(0xFF2CEEF1)

val outlineVariantLightHighContrast = Color(0xFF421222)

val scrimLightHighContrast = Color(0xFF573553)

val surfaceBrightLightHighContrast = Color(0xFF6C5884)

val surfaceContainerLightHighContrast = Color(0xFF969EE6)

val surfaceContainerHighLightHighContrast = Color(0xFFABC217)

val surfaceContainerHighestLightHighContrast = Color(0xFFC0E548)

val surfaceContainerLowLightHighContrast = Color(0xFFD60879)

val surfaceContainerLowestLightHighContrast = Color(0xFFEB2BAA)

val surfaceDimLightHighContrast = Color(0xFF817BB5)

val primaryFixedLightHighContrast = Color(0xFF004EDB)

val primaryFixedDimLightHighContrast = Color(0xFF15720C)

val onPrimaryFixedLightHighContrast = Color(0xFF2A953D)

val onPrimaryFixedVariantLightHighContrast = Color(0xFF3FB86E)

val secondaryFixedLightHighContrast = Color(0xFF54DB9F)

val secondaryFixedDimLightHighContrast = Color(0xFF69FED0)

val onSecondaryFixedLightHighContrast = Color(0xFF7F2201)

val onSecondaryFixedVariantLightHighContrast = Color(0xFF944532)

val tertiaryFixedLightHighContrast = Color(0xFFA96863)

val tertiaryFixedDimLightHighContrast = Color(0xFFBE8B94)

val onTertiaryFixedLightHighContrast = Color(0xFFD3AEC5)

val onTertiaryFixedVariantLightHighContrast = Color(0xFFE8D1F6)

val primaryDarkHighContrast = Color(0xFF87DC77)

val onPrimaryDarkHighContrast = Color(0xFF9CFFA8)

val primaryContainerDarkHighContrast = Color(0xFFB222D9)

val onPrimaryContainerDarkHighContrast = Color(0xFFC7460A)

val inversePrimaryDarkHighContrast = Color(0xFFDC693B)

val secondaryDarkHighContrast = Color(0xFFF18C6C)

val onSecondaryDarkHighContrast = Color(0xFF06AF9D)

val secondaryContainerDarkHighContrast = Color(0xFF1BD2CE)

val onSecondaryContainerDarkHighContrast = Color(0xFF30F5FF)

val tertiaryDarkHighContrast = Color(0xFF461930)

val onTertiaryDarkHighContrast = Color(0xFF5B3C61)

val tertiaryContainerDarkHighContrast = Color(0xFF705F92)

val onTertiaryContainerDarkHighContrast = Color(0xFF8582C3)

val backgroundDarkHighContrast = Color(0xFF9AA5F4)

val onBackgroundDarkHighContrast = Color(0xFFAFC925)

val surfaceDarkHighContrast = Color(0xFFC4EC56)

val onSurfaceDarkHighContrast = Color(0xFFDA0F87)

val surfaceVariantDarkHighContrast = Color(0xFFEF32B8)

val onSurfaceVariantDarkHighContrast = Color(0xFF0455E9)

val surfaceTintDarkHighContrast = Color(0xFF19791A)

val inverseSurfaceDarkHighContrast = Color(0xFF2E9C4B)

val inverseOnSurfaceDarkHighContrast = Color(0xFF43BF7C)

val errorDarkHighContrast = Color(0xFF58E2AD)

val onErrorDarkHighContrast = Color(0xFF6E05DE)

val errorContainerDarkHighContrast = Color(0xFF83290F)

val onErrorContainerDarkHighContrast = Color(0xFF984C40)

val outlineDarkHighContrast = Color(0xFFAD6F71)

val outlineVariantDarkHighContrast = Color(0xFFC292A2)

val scrimDarkHighContrast = Color(0xFFD7B5D3)

val surfaceBrightDarkHighContrast = Color(0xFFECD904)

val surfaceContainerDarkHighContrast = Color(0xFF171F66)

val surfaceContainerHighDarkHighContrast = Color(0xFF2C4297)

val surfaceContainerHighestDarkHighContrast = Color(0xFF4165C8)

val surfaceContainerLowDarkHighContrast = Color(0xFF5688F9)

val surfaceContainerLowestDarkHighContrast = Color(0xFF6BAC2A)

val surfaceDimDarkHighContrast = Color(0xFF01FC35)

val primaryFixedDarkHighContrast = Color(0xFF80CF5B)

val primaryFixedDimDarkHighContrast = Color(0xFF95F28C)

val onPrimaryFixedDarkHighContrast = Color(0xFFAB15BD)

val onPrimaryFixedVariantDarkHighContrast = Color(0xFFC038EE)

val secondaryFixedDarkHighContrast = Color(0xFFD55C1F)

val secondaryFixedDimDarkHighContrast = Color(0xFFEA7F50)

val onSecondaryFixedDarkHighContrast = Color(0xFFFFA281)

val onSecondaryFixedVariantDarkHighContrast = Color(0xFF14C5B2)

val tertiaryFixedDarkHighContrast = Color(0xFF29E8E3)

val tertiaryFixedDimDarkHighContrast = Color(0xFF3F0C14)

val onTertiaryFixedDarkHighContrast = Color(0xFF542F45)

val onTertiaryFixedVariantDarkHighContrast = Color(0xFF695276)
