// Generated by MaterialKolor Builder 2.0.0 for MaterialKolor 6.0.0.
// Open this theme in the builder at https://materialkolor.com/t/AdllOxMEACgDAAOLGhD_tKgPAf_7_xoCmoyJAQBS

package com.example.theme

import androidx.compose.foundation.isSystemInDarkTheme
import androidx.compose.material3.ExperimentalMaterial3ExpressiveApi
import androidx.compose.material3.MotionScheme
import androidx.compose.runtime.Composable
import androidx.compose.ui.graphics.Color
import com.materialkolor.PaletteStyle
import com.materialkolor.dynamiccolor.ColorSpec
import com.materialkolor.material3.DynamicMaterialExpressiveTheme
import com.materialkolor.material3.rememberDynamicMaterialThemeState

@OptIn(ExperimentalMaterial3ExpressiveApi::class)
@Composable
fun AppTheme(
    isDark: Boolean = isSystemInDarkTheme(),
    content: @Composable () -> Unit,
) {
    val state = rememberDynamicMaterialThemeState(
        seedColor = SeedColor,
        isDark = isDark,
        style = PaletteStyle.Expressive,
        specVersion = ColorSpec.SpecVersion.SPEC_2025,
        modifyColorScheme = { scheme ->
            scheme.copy(
                primary = if (isDark) Color(0xFFFFB4A8) else Color(0xFF8B1A10),
                surface = if (isDark) scheme.surface else Color(0xFFFFFBFF),
                outline = if (isDark) Color(0xFF9A8C89) else scheme.outline,
            )
        },
    )

    DynamicMaterialExpressiveTheme(
        state = state,
        motionScheme = MotionScheme.standard(),
        content = content,
    )
}
