// Generated by MaterialKolor Builder 2.0.0 for MaterialKolor 6.0.0.
// Open this theme in the builder at https://materialkolor.com/t/AdllOwACAADF

package com.example.theme

import androidx.compose.animation.core.tween
import androidx.compose.foundation.isSystemInDarkTheme
import androidx.compose.runtime.Composable
import com.materialkolor.dynamiccolor.ColorSpec
import com.materialkolor.fluent.animateFluentColors
import com.materialkolor.fluent.rememberFluentColors
import io.github.composefluent.FluentTheme

@Composable
fun AppTheme(
    isDark: Boolean = isSystemInDarkTheme(),
    content: @Composable () -> Unit,
) {
    val targetColors = rememberFluentColors(
        seedColor = SeedColor,
        isDark = isDark,
        specVersion = ColorSpec.SpecVersion.SPEC_2021,
    )
    val colors = animateFluentColors(targetColors, animationSpec = { tween(durationMillis = 500) })

    FluentTheme(
        colors = colors,
        content = content,
    )
}
