// Generated by MaterialKolor Builder 2.0.0 for MaterialKolor 6.0.0.
// Open this theme in the builder at https://materialkolor.com/t/AdllOwABAAB4

package com.example.theme

import com.composeunstyled.theme.ColorScheme
import com.composeunstyled.theme.buildThemeV2
import com.materialkolor.dynamiccolor.ColorSpec
import com.materialkolor.unstyled.MaterialKolorTokens
import com.materialkolor.unstyled.rememberDynamicLightDarkColors

val AppTheme = buildThemeV2 {
    val (light, dark) = rememberDynamicLightDarkColors(
        seedColor = SeedColor,
        specVersion = ColorSpec.SpecVersion.SPEC_2021,
    )
    properties[MaterialKolorTokens.colors] = light

    colorScheme(ColorScheme.Dark) {
        properties[MaterialKolorTokens.colors] = dark
    }
}
