// Generated by MaterialKolor Builder 2.0.0 for MaterialKolor 6.0.0.
// Open this theme in the builder at https://materialkolor.com/t/AdllOwABAAB4

package com.example.theme

import com.composeunstyled.theme.buildThemeV2
import com.materialkolor.unstyled.dynamicColorSchemes

val AppTheme = buildThemeV2 { dynamicColorSchemes(seedColor = SeedColor) }
