package com.materialkolor.builder.domain.link

import com.materialkolor.builder.domain.color.Argb
import com.materialkolor.builder.domain.color.ContrastLevel
import com.materialkolor.builder.domain.model.Accent
import com.materialkolor.builder.domain.model.CustomSlot
import com.materialkolor.builder.domain.model.CustomTone
import com.materialkolor.builder.domain.model.FamilyTones
import com.materialkolor.builder.domain.model.KeyColor
import com.materialkolor.builder.domain.model.KeyColors
import com.materialkolor.builder.domain.model.Library
import com.materialkolor.builder.domain.model.MotionSchemeChoice
import com.materialkolor.builder.domain.model.OnColorThreshold
import com.materialkolor.builder.domain.model.Role
import com.materialkolor.builder.domain.model.RolePin
import com.materialkolor.builder.domain.model.SchemePlatform
import com.materialkolor.builder.domain.model.SpecVersion
import com.materialkolor.builder.domain.model.Style
import com.materialkolor.builder.domain.model.ThemeDocument
import kotlinx.serialization.json.Json
import kotlinx.serialization.json.JsonArray
import kotlinx.serialization.json.buildJsonArray
import kotlinx.serialization.json.buildJsonObject
import kotlinx.serialization.json.put
import java.io.File
import kotlin.test.Test
import kotlin.test.assertEquals

/**
 * Writes the share code vectors that every other reader of the format checks itself against.
 *
 * The fixture holds about forty documents that between them touch every section, each beside the
 * code this codec writes for it. The domain tests read it back on every platform through the
 * generated `SHARE_VECTORS_JSON`, and the link preview Worker reads the same file.
 *
 * An ordinary run only checks that the committed files still match the codec. After a deliberate
 * change to the format, run it once with `SHARE_VECTORS_WRITE=true` in the environment to write
 * both files again, then commit them.
 */
class ShareVectorsWriter {
    private val json =
        Json {
            prettyPrint = true
            encodeDefaults = true
        }

    @Test
    fun shareVectors_committedFixture_matchesTheCodec() {
        val rendered = render(shareVectors())
        val root = repositoryRoot()
        val fixture = File(root, FIXTURE_PATH)
        val constant = File(root, CONSTANT_PATH)

        if (System.getenv(WRITE_VARIABLE) == "true" || !fixture.isFile) {
            fixture.parentFile.mkdirs()
            fixture.writeText(rendered)
            constant.writeText(renderConstant(rendered))
            println("Wrote $FIXTURE_PATH and $CONSTANT_PATH, commit both")
            return
        }

        assertEquals(rendered, fixture.readText(), "$FIXTURE_PATH is stale, run with $WRITE_VARIABLE=true")
        val stale = "is stale, run with $WRITE_VARIABLE=true"
        assertEquals(rendered.trimEnd('\n'), SHARE_VECTORS_JSON, "$CONSTANT_PATH $stale")
    }

    private fun render(vectors: List<ShareVector>): String {
        val array =
            buildJsonArray {
                vectors.forEach { vector ->
                    val code = ShareCodec.encode(vector.document, vector.projectName)
                    val decoded = ShareCodec.decode(code)
                    check(decoded == DecodeResult.Ok(vector.document, vector.projectName)) { vector.label }
                    val entry =
                        buildJsonObject {
                            put("label", vector.label)
                            put("document", json.encodeToJsonElement(ThemeDocument.serializer(), vector.document))
                            put("projectName", vector.projectName)
                            put("code", code)
                            put("seedHex", vector.document.seed.toHex())
                            put("library", vector.document.library.name)
                            put("style", vector.document.style.name)
                        }
                    add(entry)
                }
            }
        return json.encodeToString(JsonArray.serializer(), array) + "\n"
    }

    private fun renderConstant(rendered: String): String {
        // The JSON goes into a raw string, where a dollar sign or three quotes would end or change it.
        check('$' !in rendered && "\"\"\"" !in rendered) { "The vectors cannot be held in a raw string" }
        return buildString {
            appendLine("package com.materialkolor.builder.domain.link")
            appendLine()
            appendLine("// Generated by ShareVectorsWriter from builder/fixtures/share-codes.json, so the wasm")
            appendLine("// tests can read the vectors without a file system. Run the writer again rather than")
            appendLine("// editing this by hand.")
            appendLine("internal val SHARE_VECTORS_JSON: String =")
            appendLine("    \"\"\"")
            rendered.trimEnd('\n').lines().forEach { line -> appendLine("    $line") }
            appendLine("    \"\"\".trimIndent()")
        }
    }

    private fun repositoryRoot(): File =
        generateSequence(File(System.getProperty("user.dir")).absoluteFile) { directory -> directory.parentFile }
            .first { directory -> File(directory, "settings.gradle.kts").isFile && File(directory, "builder").exists() }

    private companion object {
        const val WRITE_VARIABLE: String = "SHARE_VECTORS_WRITE"
        const val FIXTURE_PATH: String = "builder/fixtures/share-codes.json"
        const val CONSTANT_PATH: String =
            "builder/domain/src/commonTest/kotlin/com/materialkolor/builder/domain/link/ShareVectorsFixture.kt"
    }
}

private class ShareVector(
    val label: String,
    val document: ThemeDocument,
    val projectName: String? = null,
)

/**
 * The documents the fixture holds. Every one is built by hand so the file only moves when the
 * format does, never because a generator changed.
 */
private fun shareVectors(): List<ShareVector> {
    val base = ThemeDocument.Default
    val violet = Argb(0x6750A4)
    val teal = Argb(0x00658E)
    val rose = Argb(0x7D5260)
    val green = Argb(0x386A20)
    val brand = Accent(name = "brand", seed = Argb(0xE91E63))
    val status =
        Accent(
            name = "status",
            seed = green,
            harmonize = false,
            light = FamilyTones(color = 35, container = 85),
            dark = FamilyTones(color = 75, container = 25),
            threshold = OnColorThreshold.Aaa,
        )
    return buildList {
        add(ShareVector("default", base))
        add(ShareVector("default with a project name", base, projectName = "Acme"))
        add(ShareVector("typed seed", base.copy(seed = violet)))
        Style.entries.forEachIndexed { index, style ->
            val seed = Argb(0x1E3A5F + index * 0x0B1D07)
            add(ShareVector("style ${style.name}", base.copy(seed = seed, style = style)))
        }
        val cmf = base.copy(style = Style.Cmf, spec = SpecVersion.Spec2026, cmfTertiarySeed = rose)
        add(ShareVector("cmf with a tertiary seed", cmf))
        add(ShareVector("cmf seed kept under another style", base.copy(cmfTertiarySeed = green)))
        val watch = base.copy(spec = SpecVersion.Spec2025, platform = SchemePlatform.Watch)
        add(ShareVector("spec 2025 on a watch", watch))
        add(ShareVector("amoled", base.copy(amoled = true)))
        val contrasts = listOf(ContrastLevel.Reduced, ContrastLevel.Medium, ContrastLevel.High, ContrastLevel(-37))
        contrasts.forEach { contrast ->
            add(ShareVector("contrast ${contrast.hundredths}", base.copy(contrast = contrast)))
        }
        Library.entries.filter { library -> library != base.library }.forEach { library ->
            add(ShareVector("library ${library.name}", base.copy(library = library)))
        }
        add(ShareVector("material3 expressive", base.copy(expressive = true)))
        add(ShareVector("one key color", base.copy(keyColors = KeyColors(primary = teal))))
        add(
            ShareVector(
                "every key color",
                base.copy(
                    keyColors =
                        KeyColor.entries.fold(KeyColors()) { colors, slot ->
                            colors.with(slot, Argb(0x102030 * (slot.code + 1)))
                        },
                ),
            ),
        )
        add(ShareVector("default accent", base.copy(accents = listOf(brand))))
        add(ShareVector("accent with its own tones and threshold", base.copy(accents = listOf(status))))
        val loose = brand.copy(threshold = OnColorThreshold.AaLarge)
        add(ShareVector("accent with only a threshold", base.copy(accents = listOf(loose))))
        add(ShareVector("accent with a non ascii name", base.copy(accents = listOf(brand.copy(name = "crème")))))
        val info = brand.copy(name = "info", seed = teal)
        add(ShareVector("three accents", base.copy(accents = listOf(brand, status, info))))
        add(ShareVector("light pin", base.copy(pins = mapOf(Role.Primary to RolePin(light = violet)))))
        add(
            ShareVector(
                "pins in every mode",
                base.copy(
                    pins =
                        mapOf(
                            Role.Surface to RolePin(dark = Argb(0x000000)),
                            Role.Error to RolePin(light = Argb(0xB3261E), dark = Argb(0xF2B8B5)),
                            Role.OnTertiaryFixedVariant to RolePin(light = rose),
                        ),
                ),
            ),
        )
        add(ShareVector("standard motion", base.copy(motionScheme = MotionSchemeChoice.Standard)))
        add(ShareVector("renamed theme", base.copy(themeName = "BrandTheme")))
        add(
            ShareVector(
                "custom tones",
                base.copy(
                    library = Library.Custom,
                    customTones =
                        mapOf(
                            CustomSlot.PrimaryPressed to CustomTone(light = 28),
                            CustomSlot.SurfaceRaised to CustomTone(dark = 10),
                            CustomSlot.BorderStrong to CustomTone(light = 50, dark = 60),
                            CustomSlot.Shadow to CustomTone(),
                        ),
                ),
            ),
        )
        add(ShareVector("longest project name", base, projectName = "x".repeat(48)))
        add(ShareVector("non ascii project name", base, projectName = "Café Olé ☕"))
        add(
            ShareVector(
                "every section at once",
                ThemeDocument(
                    seed = violet,
                    keyColors = KeyColors(secondary = teal),
                    style = Style.Cmf,
                    cmfTertiarySeed = rose,
                    contrast = ContrastLevel.Medium,
                    spec = SpecVersion.Spec2026,
                    amoled = true,
                    accents = listOf(brand),
                    pins = mapOf(Role.Primary to RolePin(light = teal)),
                    library = Library.Custom,
                    expressive = true,
                    motionScheme = MotionSchemeChoice.Standard,
                    themeName = "Kit",
                    customTones = mapOf(CustomSlot.FocusRing to CustomTone(light = 55)),
                ),
                projectName = "Kit",
            ),
        )
    }
}
