// Generated by MaterialKolor Builder 2.0.0 with colors from MaterialKolor 6.0.0.
// Open this theme in the builder at https://materialkolor.com/t/AdllOwABAAB4

package com.example.theme

import com.composeunstyled.theme.ColorScheme
import com.composeunstyled.theme.buildThemeV2

// The mediumContrast and highContrast maps in Color.kt can be swapped in for lightColors and darkColors.
val AppTheme = buildThemeV2 {
    properties[ThemeTokens.colors] = lightColors

    colorScheme(ColorScheme.Dark) {
        properties[ThemeTokens.colors] = darkColors
    }
}
