package conformance

import java.io.File

/**
 * Provenance header shared by the explicit golden-fixture generators.
 *
 * The upstream revision is read from the reviewed lock at generation time rather than hard-coded,
 * so a regenerated fixture cannot claim a revision the lock does not record. The lock path is
 * supplied by the Gradle maintenance task. A direct classpath invocation may omit it and the
 * repository root is then located by walking up from the working directory.
 */
internal object FixtureProvenance {
    private const val LOCK = "gradle/mcu-upstream.lock.json"
    private const val FIXTURES =
        "material-color-utilities/src/commonTest/kotlin/com/materialkolor/conformance"

    // One field out of a JSON document the Java reference module has no parser for. The canonical
    // reader is SourceLock.kt in :mcu-source-transformer. This must agree with it or fail.
    private val REVISION = Regex("\"upstreamRevision\"\\s*:\\s*\"([^\"]*)\"")
    private val SHA1 = Regex("[0-9a-f]{40}")

    /**
     * Comment lines recording what generated a fixture, from which pin, and how to redo it.
     */
    fun header(
        generator: String,
        task: String,
        fixture: String,
        lockPath: String?,
    ): List<String> =
        listOf(
            "// Generated by conformance.$generator. Do not hand-edit this file.",
            "// Upstream revision ${revision(lockPath)}, read from $LOCK.",
            "// Regenerate from the repository root, then format the result.",
            "//   ./gradlew -q :mcu-upstream:$task \\",
            "//     > $FIXTURES/$fixture",
            "//   ./gradlew :material-color-utilities:spotlessApply",
        )

    private fun revision(lockPath: String?): String {
        val lock = lockPath?.let(::File) ?: locateLock()
        require(lock.isFile) { "Upstream lock not found at ${lock.path}; pass its path as argument one." }
        val match = REVISION.find(lock.readText())
        requireNotNull(match) { "No upstreamRevision field in ${lock.path}." }
        val revision = match.groupValues[1]
        require(revision.matches(SHA1)) {
            "upstreamRevision in ${lock.path} is \"$revision\", not a 40-character lowercase hex commit."
        }
        return revision
    }

    private fun locateLock(): File {
        val start = File(System.getProperty("user.dir")).absoluteFile
        var directory: File? = start
        while (directory != null) {
            val candidate = File(directory, LOCK)
            if (candidate.isFile) return candidate
            directory = directory.parentFile
        }
        error("No $LOCK above $start; pass its path as argument one.")
    }
}
