// Generated by MaterialKolor Builder 2.0.0 for MaterialKolor 6.0.0.
// Open this theme in the builder at https://materialkolor.com/t/AdllO1ABZAkBZ1CkAwADixoQ_7SoDwH_-_8aApqMieo

package com.example.theme

import androidx.compose.animation.core.tween
import androidx.compose.runtime.remember
import androidx.compose.ui.graphics.Color
import com.composeunstyled.theme.ColorScheme
import com.composeunstyled.theme.buildThemeV2
import com.materialkolor.dynamiccolor.ColorSpec
import com.materialkolor.dynamiccolor.DynamicScheme
import com.materialkolor.ktx.rememberDynamicScheme
import com.materialkolor.unstyled.MaterialKolorTokens
import com.materialkolor.unstyled.toThemeValues

val AppTheme = buildThemeV2 {
    colorSchemeTransitionSpec = tween(durationMillis = 500)

    val lightScheme = rememberDynamicScheme(
        seedColor = SeedColor,
        isDark = false,
        primary = Primary,
        contrastLevel = 1.0,
        specVersion = ColorSpec.SpecVersion.SPEC_2025,
        platform = DynamicScheme.Platform.WATCH,
    )
    val darkScheme = rememberDynamicScheme(
        seedColor = SeedColor,
        isDark = true,
        primary = Primary,
        contrastLevel = 1.0,
        specVersion = ColorSpec.SpecVersion.SPEC_2025,
        platform = DynamicScheme.Platform.WATCH,
    )

    properties[MaterialKolorTokens.colors] = remember(lightScheme) {
        lightScheme.toThemeValues() + mapOf(
            MaterialKolorTokens.primary to Color(0xFF8B1A10),
            MaterialKolorTokens.surface to Color(0xFFFFFBFF),
        )
    }

    colorScheme(ColorScheme.Dark) {
        properties[MaterialKolorTokens.colors] = remember(darkScheme) {
            darkScheme.toThemeValues() + mapOf(
                MaterialKolorTokens.primary to Color(0xFFFFB4A8),
                MaterialKolorTokens.outline to Color(0xFF9A8C89),
            )
        }
    }
}
