package com.materialkolor.builder.codegen.text

import com.materialkolor.builder.codegen.ExportInput
import com.materialkolor.builder.domain.persist.ExportMode

/**
 * The comment every generated Kotlin file opens with.
 *
 * It says which builder wrote the file, how the file relates to MaterialKolor, and how to get back
 * to the theme, without a colon anywhere in the prose so it reads like a sentence rather than a form.
 * A dynamic file names the MaterialKolor it expects. A frozen file needs no MaterialKolor at all, so
 * it names the one its colors came from instead.
 */
public object Header {
    /**
     * The header lines for [input] written in [mode], without the comment markers the file writer adds.
     *
     * Each export passes its own mode rather than the one in the input's prefs, which the exports
     * leave for the caller to act on.
     */
    public fun lines(
        input: ExportInput,
        mode: ExportMode = ExportMode.Dynamic,
    ): List<String> {
        val relation = when (mode) {
            ExportMode.Dynamic -> "for"
            ExportMode.Frozen -> "with colors from"
        }

        return listOf(
            "Generated by MaterialKolor Builder ${input.versions.builder} " +
                "$relation MaterialKolor ${input.versions.materialKolor}.",
            "Open this theme in the builder at ${input.shareUrl}",
        )
    }
}
