package com.materialkolor.builder.codegen.text

import com.materialkolor.builder.codegen.ExportInput

/**
 * The comment every generated Kotlin file opens with.
 *
 * It says which builder wrote the file, which library it expects, and how to get back to the theme,
 * without a colon anywhere in the prose so it reads like a sentence rather than a form.
 */
public object Header {
    /** The header lines for [input], without the comment markers the file writer adds. */
    public fun lines(input: ExportInput): List<String> =
        listOf(
            "Generated by MaterialKolor Builder ${input.versions.builder} " +
                "for MaterialKolor ${input.versions.materialKolor}.",
            "Open this theme in the builder at ${input.shareUrl}",
        )
}
