// Generated by MaterialKolor Builder 2.0.0 for MaterialKolor 6.0.0.
// Open this theme in the builder at https://materialkolor.com/t/AdllOwABAAgDAAOLGhD_tKgPAf_7_xoCmoyJxg

package com.example.theme

import androidx.compose.ui.graphics.Color
import com.composeunstyled.theme.ColorScheme
import com.composeunstyled.theme.buildThemeV2
import com.materialkolor.ktx.rememberDynamicScheme
import com.materialkolor.unstyled.MaterialKolorTokens
import com.materialkolor.unstyled.toThemeValues

val AppTheme = buildThemeV2 {
    val lightScheme = rememberDynamicScheme(
        seedColor = SeedColor,
        isDark = false,
    )
    val darkScheme = rememberDynamicScheme(
        seedColor = SeedColor,
        isDark = true,
    )

    properties[MaterialKolorTokens.colors] = lightScheme.toThemeValues() + mapOf(
        MaterialKolorTokens.primary to Color(0xFF8B1A10),
        MaterialKolorTokens.surface to Color(0xFFFFFBFF),
    )

    colorScheme(ColorScheme.Dark) {
        properties[MaterialKolorTokens.colors] = darkScheme.toThemeValues() + mapOf(
            MaterialKolorTokens.primary to Color(0xFFFFB4A8),
            MaterialKolorTokens.outline to Color(0xFF9A8C89),
        )
    }
}
