// Generated by MaterialKolor Builder 2.0.0 with colors from MaterialKolor 6.0.0.
// Open this theme in the builder at https://materialkolor.com/t/AdllOwADAACu

package com.example.theme

import androidx.compose.foundation.isSystemInDarkTheme
import androidx.compose.runtime.Composable
import androidx.compose.runtime.CompositionLocalProvider
import androidx.compose.runtime.staticCompositionLocalOf

val LocalThemeColors = staticCompositionLocalOf<ThemeColors> { error("ThemeColors are only provided inside AppTheme") }

@Composable
fun AppTheme(
    isDark: Boolean = isSystemInDarkTheme(),
    content: @Composable () -> Unit,
) {
    val colors = if (isDark) darkThemeColors else lightThemeColors

    CompositionLocalProvider(LocalThemeColors provides colors, content = content)
}
