name: CI

on:
  workflow_dispatch:
  push:
    branches:
      - main
      - preview
    paths-ignore:
      - '**.md'
  pull_request:
    branches:
      - main
    types: [ opened, synchronize, reopened, ready_for_review ]
    paths-ignore:
      - 'art/**'
      - '**.md'

concurrency:
  group: build-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: write

jobs:
  verify:
    name: "Verify"
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v5
        with:
          submodules: recursive

      - name: setup-java
        uses: actions/setup-java@v5
        with:
          java-version: 17
          distribution: adopt

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v5

      - name: Gradle Wrapper Validation
        uses: gradle/wrapper-validation-action@v3

      - name: Binary Compatibility Validation
        run: ./gradlew apiCheck --scan

      - name: Lint
        run: ./gradlew lint --scan

      - name: Upstream Tests
        run: ./gradlew :mcu-upstream:test --scan
