name: CI

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths-ignore:
      - '**.md'
  pull_request:
    branches:
      - main
    types: [ opened, synchronize, reopened, ready_for_review ]
    paths-ignore:
      - 'art/**'
      - '**.md'

concurrency:
  group: build-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: write

jobs:
  verify:
    name: "Verify"
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: setup-java
        uses: actions/setup-java@v3
        with:
          java-version: 17
          distribution: adopt

      - name: Cache Gradle
        uses: actions/cache@v3
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle-

      - name: Gradle Wrapper Validation
        uses: gradle/wrapper-validation-action@v1

      - name: Lint
        uses: gradle/gradle-build-action@v2
        with:
          arguments: lint --scan

  build:
    strategy:
      matrix:
        config: [
          { target: "android", os: "ubuntu-latest", tasks: ":demo:composeApp:assembleRelease", continueOnError: false },
          { target: "osx-desktop", os: "macos-latest", tasks: ":demo:composeApp:packageDistributionForCurrentOS", continueOnError: false },
          { target: "windows-desktop", os: "windows-latest", tasks: ":demo:composeApp:packageDistributionForCurrentOS", continueOnError: true },
          { target: "linux-desktop", os: "ubuntu-latest", tasks: ":demo:composeApp:packageDistributionForCurrentOS", continueOnError: false }
        ]
    runs-on: ${{ matrix.config.os }}
    name: Build ${{ matrix.config.target }}
    needs: verify
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: setup-java
        uses: actions/setup-java@v3
        with:
          java-version: 17
          distribution: adopt

      - name: Cache Gradle
        uses: actions/cache@v3
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle-

      - name: Cache Konan
        uses: actions/cache@v3
        with:
          path: |
            ~/.konan/caches
            ~/.konan/dependencies
            ~/.konan/kotlin-native-prebuilt-macos-*
          key: ${{ runner.os }}-konan-${{ hashFiles('**/gradle/libs.versions.toml') }}
          restore-keys: |
            ${{ runner.os }}-konan-

      - name: Build ${{ matrix.config.target }} targets
        continue-on-error: ${{ matrix.config.continueOnError }}
        uses: gradle/gradle-build-action@v2
        with:
          arguments: ${{ matrix.config.tasks }} --scan
