name: Upstream changes

on:
  # Run at 3AM every monday
  schedule:
    - cron: "0 3 * * *"
  workflow_dispatch:

permissions:
  contents: read
  issues: write

jobs:
  check:
    name: "Check upstream for changes"
    runs-on: ubuntu-latest
    steps:
      - name: Checkout project
        uses: actions/checkout@v7
        with:
          submodules: recursive

      - name: Check for upstream changes
        run: ./.github/check-upstream --token "$UPSTREAM_GITHUB_TOKEN"
        env:
          UPSTREAM_GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
